define([], function () {
  return {
    PropertyPaneDescription: 'Settings for the Invite Guests web part.',
    BasicGroupName: 'General',
    TitleFieldLabel: 'Title',
    DescriptionFieldLabel: 'Description',
    WebPartTitleInfoLabelTitle: 'More info: {0}',
    DisplayModeFieldLabel: 'Invitation status display',
    DisplayModeInlineLabel: 'Show status list in web part',
    DisplayModeDialogLabel: 'Show in dialog (compact)',
    InviteModeFieldLabel: 'Invitation mode',
    InviteModeSingleLabel: 'One guest at a time',
    InviteModeMultiLabel: 'Multiple guests at a time',
    InviteAccessLevelFieldLabel: 'Who can invite guests',
    InviteAccessLevelOwnerLabel: 'Group owners only',
    InviteAccessLevelMemberLabel: 'Owners and members',
    InviteAccessLevelAnyoneLabel: 'Anyone with site access',
    PerGuestProfileModeFieldLabel: 'Per-guest profile details',
    PerGuestRoleModeFieldLabel: 'Per-guest role/group',
    FeatureModeDisabledLabel: 'Off (hide switch)',
    FeatureModeOptionalLabel: 'Optional (user controls, default off)',
    FeatureModeEnforcedLabel: 'Enforced (always on)',
    PerGuestProfileLabel: 'Per-guest details',
    PerGuestRoleLabel: 'Per-guest role and group',
    ViewSettingsLabel: 'View options',
    ViewStatusButton: 'View invitation status',
    StatusDialogTitle: 'Invitation status',
    StatusSummaryTotal: '{0} total',
    StatusSummaryPending: '{0} pending',
    StatusSummaryFailed: '{0} failed',
    CloseButton: 'Close',
    GuestRequestListTitleFieldLabel: 'Guest request list title',
    GuestRequestListTitleFieldDescription: 'The SharePoint list where invitation requests are stored. Default: Guest Requests',
    GuestRequestSiteUrlFieldLabel: 'Bestillingsportalen site URL',
    GuestRequestSiteUrlFieldDescription: 'URL of the site where the Guest Requests list lives (typically Bestillingsportalen). Leave blank to use the current site.',

    InviteButton: 'Invite guests',
    InviteDrawerHeader: 'Invite guests to this site',
    InviteDrawerDescription: 'Enter one or more email addresses. Each guest receives an invitation and shows up in the list below once processed.',
    GuestPickerLabel: 'Email address',
    GuestPickerPlaceholder: 'Type an email address',
    GuestPickerInvalidEmail: 'Invalid email address',
    GuestPickerNoOptionsText: 'Enter a valid email address',
    GuestPickerHelperText: 'Separate multiple emails with comma, semicolon or newline. If the person exists in Microsoft Entra, profile information is fetched automatically.',
    FirstNameLabel: 'First name',
    FirstNameDescription: 'The guest first name as it will appear in Microsoft Entra.',
    LastNameLabel: 'Last name',
    LastNameDescription: 'The guest last name as it will appear in Microsoft Entra.',
    CompanyLabel: 'Company / organization',
    CompanyDescription: 'The company or organization the guest represents.',
    GuestExistsBadge: 'Exists in Entra ID',
    GuestExistsMissingDetails: 'Exists in Entra ID, but missing first name and/or last name. Ask an administrator to update the user profile if needed.',
    NoValuePlaceholder: 'No value',
    AccessPreviewTitle: 'Access the guest will receive:',
    AccessPreviewWarningFooter: 'Consider whether this is necessary — a more limited role gives safer external access.',
    AccessFullAdminGroupConnected: 'Owner of the Microsoft 365 group (can manage Teams, channels and members)',
    AccessFullAdminSiteOnly: 'Full administrator access to the SharePoint site',
    AccessSiteEdit: 'Edit access on the SharePoint site',
    AccessSiteRead: 'Read access on the SharePoint site (via the Visitors group)',
    AccessNoM365: 'No automatic access from the Microsoft 365 group',
    AccessTeamsMember: 'Teams member (chat and all channels)',
    AccessOneNotePlannerCalendar: 'Access to OneNote, Planner and group calendar',
    AccessCanInviteOthers: 'Can invite other guests to the site',
    AccessNotGroupConnectedNote: 'Site is not connected to a Microsoft 365 group, so no Teams/OneNote/Planner access.',
    AccessSpGroupAddTemplate: 'Added to the SharePoint group "{0}"',
    AccessSpGroupCreateTemplate: 'Access via new SharePoint group "{0}" with permission "{1}"',
    CancelButton: 'Cancel',
    SendInvitationsButton: 'Send invitations',
    RefreshButton: 'Refresh',
    RetryButton: 'Retry',

    StatusHeader: 'Invitation status',
    StatusEmpty: 'No invitations recorded for this site yet.',
    StatusSearchPlaceholder: 'Search by email …',

    ColumnEmail: 'Email',
    ColumnStatus: 'Status',
    ColumnRequestedBy: 'Requested by',
    ColumnCreated: 'Sent',
    ColumnError: 'Error',
    CopyRedeemUrlLabel: 'Copy invitation link',
    CopyRedeemUrlCopied: 'Copied!',

    StatusPending: 'Pending',
    StatusInvited: 'Invited',
    StatusFailed: 'Failed',

    ToastSuccessTitle: 'Invitations sent',
    ToastSuccessBody: 'The requests have been recorded and are being processed in the background.',
    ToastErrorTitle: 'Could not send invitations',
    ToastErrorBody: 'An error occurred. Check the console for details.',

    M365GroupSectionTitle: 'Site role',
    M365GroupRoleNoneLabel: 'No role',
    M365GroupRoleVisitorLabel: 'Visitor',
    M365GroupRoleMemberLabel: 'Member',
    M365GroupRoleOwnerLabel: 'Owner',
    M365GroupRoleSectionDescription: 'On Microsoft 365 group-connected sites Owner and Member are handled via the group (auto-synced); Visitor is always handled via the SharePoint group. On other site types, all roles are handled directly via the SharePoint groups.',

    SPGroupSectionTitle: 'SharePoint user group (optional)',
    SPGroupActionNoneLabel: 'Do not add to a SharePoint group',
    SPGroupActionExistingLabel: 'Add to an existing group',
    SPGroupActionNewLabel: 'Create a new group',
    SPGroupExistingPickerLabel: 'Choose group',
    SPGroupExistingPickerPlaceholder: 'Pick a SharePoint group …',
    SPGroupNewNameLabel: 'New group name',
    SPGroupNewNamePlaceholder: 'e.g. External collaborators',
    SPGroupNewPermissionLabel: 'Permission level',
    SPGroupNewNameRequired: 'Group name is required',

    SPPermissionRead: 'Read',
    SPPermissionContribute: 'Contribute',
    SPPermissionEdit: 'Edit',
    SPPermissionFullControl: 'Full Control',

    ColumnM365GroupRole: 'M365 role',
    ColumnSPGroupAction: 'SP group action',
    ColumnSPGroupName: 'SP group',
    ColumnSPPermissionLevel: 'Permission level'
  };
});
