define([], function () {
  return {
    PropertyPaneDescription: 'Settings for the Invite Guests web part.',
    BasicGroupName: 'General',
    GeneralGroupName: 'General',
    InviteSettingsGroupName: 'Invitation settings',
    PerGuestGroupName: 'Per-guest features',
    DefaultsGroupName: 'Defaults',
    ShowHideGroupName: 'Show/Hide',
    DrawerShowHideGroupName: 'Show/Hide in invite drawer',
    StatusShowHideGroupName: 'Show/Hide in invitation status',
    AdvancedGroupName: 'Advanced',
    BooleanOn: 'On',
    BooleanOff: 'Off',
    DefaultM365GroupRoleFieldLabel: 'Default M365 role',
    DefaultM365GroupRoleFieldDescription: 'Pre-selected role when the invite drawer opens. Guest = guest member of the Microsoft 365 group (the standard guest access in Microsoft 365); externals can never be owners.',
    DefaultSpGroupActionFieldLabel: 'Default SP group action',
    DefaultSpGroupActionFieldDescription: 'Pre-selected SharePoint user group action. Default is "Do not add" — the Guest role already grants access via the M365 group. "Add to existing" will pre-select the site Visitors group (see also Auto-select Visitors group).',
    DefaultSpGroupNameFieldLabel: 'Default SP group name',
    DefaultSpGroupNameFieldDescription: 'Name of a specific SharePoint group to pre-select when "Add to existing" is chosen. If empty, the Visitors group is used (when Auto-select is on). The group must exist on the site.',
    PresetSpGroupNameFieldLabel: 'Preset SP group',
    PresetSpGroupNameFieldDescription: 'Name of a SharePoint group. When set, a fourth option appears in the drawer that adds the guest to exactly this group — without a dropdown. Empty = the option is hidden. The group must exist on the site.',
    SPGroupActionPresetTemplate: 'Add to "{0}"',
    SPGroupActionPresetLabel: 'Preset group',
    SpGroupOptionsGroupName: 'SharePoint group options',
    ShowSpActionNoneFieldLabel: 'Show option: Do not add',
    ShowSpActionExistingFieldLabel: 'Show option: Add to existing',
    ShowSpActionNewFieldLabel: 'Show option: Create new group',
    ShowSpActionPresetFieldLabel: 'Show option: Preset group',
    SpGroupActionOrderFieldLabel: 'Option order',
    SpGroupActionOrderFieldDescription: 'Drag to reorder the SP group options shown in the drawer. Visibility is controlled by the toggles above.',
    DefaultSpPermissionLevelFieldLabel: 'Default permission level',
    DefaultSpPermissionLevelFieldDescription: 'Pre-selected permission level when "Create new group" is chosen. Only applies when default SP group action = Create new group.',
    AutoSelectVisitorGroupFieldLabel: 'Auto-select Visitors group',
    AutoSelectVisitorGroupFieldDescription: 'Pre-fill the site Visitors group when the drawer opens (only when default SP group action = Add to existing).',
    LockM365GroupRoleFieldLabel: 'Lock default M365 role',
    LockM365GroupRoleFieldDescription: 'Hide the role choices in the drawer so users only see the default role (cannot be changed).',
    LockSpGroupActionFieldLabel: 'Lock default SP group action',
    LockSpGroupActionFieldDescription: 'Hide the SP group action choices in the drawer so users only see the default action (cannot be changed). Sub-fields (group picker, new group name, permission level) remain editable.',
    LockedRoleLabel: 'Role: {0}',
    LockedActionLabel: 'Action: {0}',
    LockedGroupNameLabel: 'Group: {0}',
    LockedFieldTooltip: 'Locked by administrator — cannot be changed.',
    ShowAccessPreviewFieldLabel: 'Show access preview in drawer',
    ShowStatusSummaryFieldLabel: 'Show status summary (total/pending/failed)',
    ShowCopyRedeemUrlFieldLabel: 'Show Copy invitation link button',
    ShowRetryButtonFieldLabel: 'Show Retry button',
    ShowColumnM365RoleFieldLabel: 'Show column: M365 role',
    ShowColumnSPGroupActionFieldLabel: 'Show column: SP group action',
    ShowColumnSPGroupNameFieldLabel: 'Show column: SP group',
    ShowColumnSPPermissionLevelFieldLabel: 'Show column: Permission level',
    ShowM365GroupRoleSectionFieldLabel: 'Show section: Site role',
    ShowSPGroupSectionFieldLabel: 'Show section: SharePoint user group',
    TitleFieldLabel: 'Title',
    DescriptionFieldLabel: 'Description',
    WebPartTitleInfoLabelTitle: 'More info: {0}',
    DisplayModeFieldLabel: 'Invitation status display',
    DisplayModeInlineLabel: 'Show status list in web part',
    DisplayModeDialogLabel: 'Show in dialog (compact)',
    InviteModeFieldLabel: 'Invitation mode',
    InviteModeSingleLabel: 'One guest at a time',
    InviteModeMultiLabel: 'Multiple guests at a time',
    InviteAccessLevelFieldLabel: 'Who can invite guests',
    InviteAccessLevelOwnerLabel: 'Group owners only',
    InviteAccessLevelMemberLabel: 'Owners and members',
    InviteAccessLevelAnyoneLabel: 'Anyone with site access',
    PerGuestProfileModeFieldLabel: 'Per-guest profile details',
    PerGuestRoleModeFieldLabel: 'Per-guest role/group',
    FeatureModeDisabledLabel: 'Off (hide switch)',
    FeatureModeOptionalLabel: 'Optional (user controls, default off)',
    FeatureModeEnforcedLabel: 'Enforced (always on)',
    PerGuestProfileLabel: 'Per-guest details',
    PerGuestRoleLabel: 'Per-guest role and group',
    ViewSettingsLabel: 'View options',
    ViewStatusButton: 'View invitation status',
    StatusDialogTitle: 'Invitation status',
    StatusSummaryTotal: '{0} total',
    StatusSummaryPending: '{0} pending',
    StatusSummaryFailed: '{0} failed',
    CloseButton: 'Close',
    GuestRequestListTitleFieldLabel: 'Guest request list title',
    GuestRequestListTitleFieldDescription: 'The SharePoint list where invitation requests are stored. Default: Guest Requests',
    GuestRequestSiteUrlFieldLabel: 'Bestillingsportalen site URL',
    GuestRequestSiteUrlFieldDescription: 'URL of the site where the Guest Requests list lives. Leave blank to use /sites/bestillingsportalen on the current tenant (the deployment default alias).',
    HiddenSpGroupsFieldLabel: 'Hide SharePoint groups',
    HiddenSpGroupsFieldDescription: 'Comma- or newline-separated list of groups to hide from the group picker. Matches on group name (partial) or permission level (exact). Example: Owners, Full Control.',
    AllowedSpGroupsFieldLabel: 'Show only SharePoint groups',
    AllowedSpGroupsFieldDescription: 'Comma- or newline-separated list. When set, shows ONLY matching groups (name partial, or permission level exact). Empty = show all. Combined with "Hide SharePoint groups" (hide wins). Example: External, Read.',

    InviteButton: 'Invite guests',
    InviteDrawerHeader: 'Invite guests to this site',
    InviteDrawerDescription: 'Enter one or more email addresses. Each guest receives an invitation and shows up in the list below once processed.',
    GuestPickerLabel: 'Email address',
    GuestPickerPlaceholder: 'Type an email address',
    GuestPickerInvalidEmail: 'Invalid email address',
    GuestPickerNoOptionsText: 'Enter a valid email address',
    GuestPickerHelperText: 'Separate multiple emails with comma, semicolon or newline. If the person exists in Microsoft Entra, profile information is fetched automatically.',
    FirstNameLabel: 'First name',
    FirstNameDescription: 'The guest first name as it will appear in Microsoft Entra.',
    LastNameLabel: 'Last name',
    LastNameDescription: 'The guest last name as it will appear in Microsoft Entra.',
    CompanyLabel: 'Company / organization',
    CompanyDescription: 'The company or organization the guest represents.',
    GuestExistsBadge: 'Exists in Entra ID',
    GuestExistsMissingDetails: 'Exists in Entra ID, but missing first name and/or last name. Ask an administrator to update the user profile if needed.',
    NoValuePlaceholder: 'No value',
    AccessPreviewTitle: 'Access the guest will receive:',
    AccessNoM365: 'No automatic access from the Microsoft 365 group',
    AccessNoSiteAccessWarning: 'The user gets no access to the site — only the invitation to the organization. Choose the Guest role, add the user to a SharePoint group, or share content directly later.',
    AccessSiteEdit: 'Edit access on the SharePoint site',
    AccessTeamsMember: 'Teams member (chat and all channels)',
    AccessOneNotePlannerCalendar: 'Access to OneNote, Planner and group calendar',
    AccessNotGroupConnectedNote: 'Site is not connected to a Microsoft 365 group, so no Teams/OneNote/Planner access.',
    AccessSpGroupAddTemplate: 'Added to the SharePoint group "{0}"',
    AccessSpGroupCreateTemplate: 'Access via new SharePoint group "{0}" with permission "{1}"',
    CancelButton: 'Cancel',
    ClearFieldLabel: 'Clear field',
    SendInvitationsButton: 'Send invitations',
    RefreshButton: 'Refresh',
    RetryButton: 'Retry',

    StatusHeader: 'Invitation status',
    StatusEmpty: 'No invitations recorded for this site yet.',
    StatusSearchPlaceholder: 'Search by email …',
    StatusDialogDescription: 'Overview of invitations sent from this site. Use search and commands to filter and manage invitations.',
    StatusDialogNoResultsLabel: 'No invitations recorded for this site yet.',
    StatusDialogNoSearchResultsLabel: 'No invitations matched your search.',
    StatusDialogSpinnerLabel: 'Loading invitations …',

    ColumnEmail: 'Email',
    ColumnStatus: 'Status',
    ColumnRequestedBy: 'Requested by',
    ColumnCreated: 'Sent',
    ColumnError: 'Error',
    CopyRedeemUrlLabel: 'Copy invitation link',
    CopyRedeemUrlCopied: 'Copied!',

    StatusPending: 'Pending',
    StatusInvited: 'Invited',
    StatusFailed: 'Failed',

    ToastSuccessTitle: 'Invitations sent',
    ToastSuccessBody: 'The requests have been recorded and are being processed in the background.',
    ToastErrorTitle: 'Could not send invitations',
    ToastErrorBody: 'An error occurred. Check the console for details.',

    M365GroupSectionTitle: 'Site role',
    M365GroupRoleNoneLabel: 'No role',
    M365GroupRoleVisitorLabel: 'Visitor',
    M365GroupRoleMemberLabel: 'Guest',
    M365GroupRoleOwnerLabel: 'Owner',
    M365GroupRoleSectionDescription: 'Guest adds the user as a guest member of the Microsoft 365 group — the standard model for externals in Microsoft 365. The guest then gets access to the site and the group resources (Teams, Planner, OneNote). Guests cannot be owners. Choose No role and a SharePoint group below for more limited access.',

    SPGroupSectionTitle: 'SharePoint user group (optional)',
    SPGroupSectionDescriptionWithGuestRole: 'The guest already gets access via the Microsoft 365 group (which is a member of the site members group). Use this only to add the guest to another SharePoint group as well.',
    SPGroupSectionDescriptionNoRole: 'Without the Guest role, the user only gets access to the site through a SharePoint group here — or by sharing content directly with the user later.',
    SPGroupActionNoneLabel: 'Do not add to a SharePoint group',
    SPGroupActionNoneWithGuestRoleLabel: 'Only add to the standard SharePoint group',
    SPGroupActionExistingLabel: 'Add to an existing group',
    SPGroupActionNewLabel: 'Create a new group',
    SPGroupExistingPickerLabel: 'Choose group',
    SPGroupExistingPickerPlaceholder: 'Pick a SharePoint group …',
    SPGroupNewNameLabel: 'New group name',
    SPGroupNewNamePlaceholder: 'e.g. External collaborators',
    SPGroupNewPermissionLabel: 'Permission level',
    SPGroupNewNameRequired: 'Group name is required',

    SPPermissionRead: 'Read',
    SPPermissionContribute: 'Contribute',
    SPPermissionEdit: 'Edit',
    SPPermissionFullControl: 'Full Control',

    ColumnM365GroupRole: 'M365 role',
    ColumnSPGroupAction: 'SP group action',
    ColumnSPGroupName: 'SP group',
    ColumnSPPermissionLevel: 'Permission level'
  };
});
