define([], function () {
  return {
    "PropertyPaneDescription": "Settings for the Invite Guests web part.",
    "BasicGroupName": "General",
    "GeneralGroupName": "General",
    "InviteSettingsGroupName": "Invitation settings",
    "PerGuestGroupName": "Per-guest features",
    "DefaultsGroupName": "Defaults",
    "ShowHideGroupName": "Show/Hide",
    "DrawerShowHideGroupName": "Show/Hide in invite drawer",
    "StatusShowHideGroupName": "Show/Hide in invitation status",
    "AdvancedGroupName": "Advanced",
    "BooleanOn": "On",
    "BooleanOff": "Off",
    "DefaultM365GroupRoleFieldLabel": "Default M365 role",
    "DefaultM365GroupRoleFieldDescription": "Pre-selected role when the invite drawer opens. Guest = guest member of the Microsoft 365 group (the standard guest access in Microsoft 365); externals can never be owners.",
    "DefaultSpGroupActionFieldLabel": "Default SP group action",
    "DefaultSpGroupActionFieldDescription": "Pre-selected SharePoint user group action. Default is \"Do not add\" — the Guest role already grants access via the M365 group. \"Add to existing\" will pre-select the site Visitors group (see also Auto-select Visitors group).",
    "DefaultSpGroupNameFieldLabel": "Default SP group name",
    "DefaultSpGroupNameFieldDescription": "Name of a specific SharePoint group to pre-select when \"Add to existing\" is chosen. If empty, the Visitors group is used (when Auto-select is on). The group must exist on the site.",
    "PresetSpGroupNameFieldLabel": "Preset SP group",
    "PresetSpGroupNameFieldDescription": "Name of a SharePoint group. When set, a fourth option appears in the drawer that adds the guest to exactly this group — without a dropdown. Empty = the option is hidden. The group must exist on the site.",
    "SPGroupActionPresetTemplate": "Add to \"{0}\"",
    "SPGroupActionPresetLabel": "Preset group",
    "SpGroupOptionsGroupName": "SharePoint group options",
    "ShowSpActionNoneFieldLabel": "Show option: Do not add",
    "ShowSpActionExistingFieldLabel": "Show option: Add to existing",
    "ShowSpActionNewFieldLabel": "Show option: Create new group",
    "ShowSpActionPresetFieldLabel": "Show option: Preset group",
    "ShowSpActionsDescription": "The toggles above control which SP group options appear in the invite drawer. With all off, only “Do not add” is shown. “Preset group” additionally requires a Preset SP group under Defaults.",
    "SpGroupActionOrderFieldLabel": "Option order",
    "SpGroupActionOrderFieldDescription": "Drag to reorder the SP group options shown in the drawer. Visibility is controlled by the toggles above.",
    "DefaultSpPermissionLevelFieldLabel": "Default permission level",
    "DefaultSpPermissionLevelFieldDescription": "Pre-selected permission level when \"Create new group\" is chosen. Only applies when default SP group action = Create new group.",
    "AutoSelectVisitorGroupFieldLabel": "Auto-select Visitors group",
    "AutoSelectVisitorGroupFieldDescription": "Pre-fill the site Visitors group when the drawer opens (only when default SP group action = Add to existing).",
    "LockM365GroupRoleFieldLabel": "Lock default M365 role",
    "LockM365GroupRoleFieldDescription": "Hide the role choices in the drawer so users only see the default role (cannot be changed).",
    "LockSpGroupActionFieldLabel": "Lock default SP group action",
    "LockSpGroupActionFieldDescription": "Hide the SP group action choices in the drawer so users only see the default action (cannot be changed). Sub-fields (group picker, new group name, permission level) remain editable.",
    "LockedRoleLabel": "Role: {0}",
    "LockedActionLabel": "Action: {0}",
    "LockedGroupNameLabel": "Group: {0}",
    "LockedFieldTooltip": "Locked by administrator — cannot be changed.",
    "ShowAccessPreviewFieldLabel": "Show access preview in drawer",
    "ShowAccessPreviewFieldDescription": "Shows the “Access the guest will receive” box in the drawer — a summary of what the chosen settings actually grant the guest.",
    "ShowStatusSummaryFieldLabel": "Show status summary (total/pending/failed)",
    "ShowStatusSummaryFieldDescription": "Shows counters for total/pending/failed next to the button that opens the status list. Applies to the compact (dialog) view only.",
    "ShowCopyRedeemUrlFieldLabel": "Show Copy invitation link button",
    "ShowCopyRedeemUrlFieldDescription": "Shows a button in the status list that copies the guest redemption link — useful if the invitation email did not arrive.",
    "ShowRetryButtonFieldLabel": "Show Retry button",
    "ShowRetryButtonFieldDescription": "Shows “Retry” on failed invitations. Creates a new request with the same values and recycles the failed one.",
    "ShowColumnM365RoleFieldLabel": "Show column: M365 role",
    "ShowColumnSPGroupActionFieldLabel": "Show column: SP group action",
    "ShowColumnSPGroupNameFieldLabel": "Show column: SP group",
    "StatusColumnsDescription": "The column toggles control which details are shown per invitation in the status list, in addition to guest, status and date.",
    "ShowColumnSPPermissionLevelFieldLabel": "Show column: Permission level",
    "ShowM365GroupRoleSectionFieldLabel": "Show section: Site role",
    "ShowM365GroupRoleSectionFieldDescription": "Shows the role section in the drawer. Hidden = the default role is used for every invitation without the sender seeing or changing it.",
    "ShowSPGroupSectionFieldLabel": "Show section: SharePoint user group",
    "ShowSPGroupSectionFieldDescription": "Shows the SP group section in the drawer. Hidden = the default SP group action is used for every invitation.",
    "TitleFieldLabel": "Title",
    "TitleFieldDescription": "The heading shown at the top of the web part.",
    "DescriptionFieldLabel": "Description",
    "DescriptionFieldDescription": "Intro text shown below the title. Empty = hidden.",
    "WebPartTitleInfoLabelTitle": "More info: {0}",
    "DisplayModeFieldLabel": "Invitation status display",
    "DisplayModeInlineLabel": "Show status list in web part",
    "DisplayModeDialogLabel": "Show in dialog (compact)",
    "DisplayModeFieldDescription": "How the list of previous invitations is shown: the full table directly in the web part, or compact with a summary and a button that opens the table in a dialog.",
    "InviteModeFieldLabel": "Invitation mode",
    "InviteModeSingleLabel": "One guest at a time",
    "InviteModeMultiLabel": "Multiple guests at a time",
    "InviteModeFieldDescription": "Whether the sender can add one or several email addresses per submission. With multiple guests, one request is created per guest.",
    "InviteAccessLevelFieldLabel": "Who can invite guests",
    "InviteAccessLevelOwnerLabel": "Group owners only",
    "InviteAccessLevelMemberLabel": "Owners and members",
    "InviteAccessLevelAnyoneLabel": "Anyone with site access",
    "InviteAccessLevelFieldDescription": "Who sees the web part and can invite guests. Users not meeting the requirement see nothing — the web part is hidden entirely for them.",
    "PerGuestProfileModeFieldLabel": "Per-guest profile details",
    "PerGuestRoleModeFieldLabel": "Per-guest role/group",
    "FeatureModeDisabledLabel": "Off (hide switch)",
    "FeatureModeOptionalLabel": "Optional (user controls, default off)",
    "FeatureModeEnforcedLabel": "Enforced (always on)",
    "PerGuestProfileModeFieldDescription": "Profile fields (first name, last name, company) per guest. Disabled = never shown; Optional = the sender can turn them on in the drawer; Enforced = always shown.",
    "PerGuestRoleModeFieldDescription": "Role and SP group per guest instead of shared for the whole submission. Disabled = shared choices; Optional = the sender can turn it on; Enforced = always per guest.",
    "PerGuestProfileLabel": "Per-guest details",
    "PerGuestRoleLabel": "Per-guest role and group",
    "ViewSettingsLabel": "View options",
    "ViewStatusButton": "View invitation status",
    "StatusDialogTitle": "Invitation status",
    "StatusSummaryTotal": "{0} total",
    "StatusSummaryPending": "{0} pending",
    "StatusSummaryFailed": "{0} failed",
    "CloseButton": "Close",
    "GuestRequestListTitleFieldLabel": "Guest request list title",
    "GuestRequestListTitleFieldDescription": "The SharePoint list where invitation requests are stored. Default: Guest Requests",
    "GuestRequestSiteUrlFieldLabel": "Bestillingsportalen site URL",
    "GuestRequestSiteUrlFieldDescription": "URL of the site where the Guest Requests list lives. Leave blank to use /sites/bestillingsportalen on the current tenant (the deployment default alias).",
    "HiddenSpGroupsFieldLabel": "Hide SharePoint groups",
    "HiddenSpGroupsFieldDescription": "Comma- or newline-separated list of groups to hide from the group picker. Matches on group name (partial) or permission level (exact). Example: Owners, Full Control.",
    "AllowedSpGroupsFieldLabel": "Show only SharePoint groups",
    "AllowedSpGroupsFieldDescription": "Comma- or newline-separated list. When set, shows ONLY matching groups (name partial, or permission level exact). Empty = show all. Combined with \"Hide SharePoint groups\" (hide wins). Example: External, Read.",
    "InviteButton": "Invite guests",
    "InviteDrawerHeader": "Invite guests to this site",
    "InviteDrawerDescription": "Enter one or more email addresses. Each guest receives an invitation and shows up in the list below once processed.",
    "GuestPickerLabel": "Email address",
    "GuestPickerPlaceholder": "Type an email address",
    "GuestPickerInvalidEmail": "Invalid email address",
    "GuestPickerNoOptionsText": "Enter a valid email address",
    "GuestPickerHelperText": "Separate multiple emails with comma, semicolon or newline. If the person exists in Microsoft Entra, profile information is fetched automatically.",
    "FirstNameLabel": "First name",
    "FirstNameDescription": "The guest first name as it will appear in Microsoft Entra.",
    "LastNameLabel": "Last name",
    "LastNameDescription": "The guest last name as it will appear in Microsoft Entra.",
    "CompanyLabel": "Company / organization",
    "CompanyDescription": "The company or organization the guest represents.",
    "GuestExistsBadge": "Exists in Entra ID",
    "GuestExistsMissingDetails": "Exists in Entra ID, but missing first name and/or last name. Ask an administrator to update the user profile if needed.",
    "NoValuePlaceholder": "No value",
    "AccessPreviewTitle": "Access the guest will receive:",
    "AccessNoM365": "No automatic access from the Microsoft 365 group",
    "AccessNoSiteAccessWarning": "The user gets no access to the site — only the invitation to the organization. Choose the Guest role, add the user to a SharePoint group, or share content directly later.",
    "AccessSiteEdit": "Edit access on the SharePoint site",
    "AccessTeamsMember": "Teams member (chat and all channels)",
    "AccessOneNotePlannerCalendar": "Access to OneNote, Planner and group calendar",
    "AccessNotGroupConnectedNote": "Site is not connected to a Microsoft 365 group, so no Teams/OneNote/Planner access.",
    "AccessSpGroupAddTemplate": "Added to the SharePoint group \"{0}\"",
    "AccessSpGroupCreateTemplate": "Access via new SharePoint group \"{0}\" with permission \"{1}\"",
    "CancelButton": "Cancel",
    "ClearFieldLabel": "Clear field",
    "SendInvitationsButton": "Send invitations",
    "RefreshButton": "Refresh",
    "RetryButton": "Retry",
    "StatusHeader": "Invitation status",
    "StatusEmpty": "No invitations recorded for this site yet.",
    "StatusSearchPlaceholder": "Search by email …",
    "StatusDialogDescription": "Overview of invitations sent from this site. Use search and commands to filter and manage invitations.",
    "StatusDialogNoResultsLabel": "No invitations recorded for this site yet.",
    "StatusDialogNoSearchResultsLabel": "No invitations matched your search.",
    "StatusDialogSpinnerLabel": "Loading invitations …",
    "ColumnEmail": "Email",
    "ColumnStatus": "Status",
    "ColumnRequestedBy": "Requested by",
    "ColumnCreated": "Sent",
    "ColumnError": "Error",
    "CopyRedeemUrlLabel": "Copy invitation link",
    "CopyRedeemUrlCopied": "Copied!",
    "StatusPending": "Pending",
    "StatusInvited": "Invited",
    "StatusFailed": "Failed",
    "ToastSuccessTitle": "Invitations sent",
    "ToastSuccessBody": "The requests have been recorded and are being processed in the background.",
    "ToastErrorTitle": "Could not send invitations",
    "ToastErrorBody": "An error occurred. Check the console for details.",
    "M365GroupSectionTitle": "Site role",
    "M365GroupRoleNoneLabel": "No role",
    "M365GroupRoleVisitorLabel": "Visitor",
    "M365GroupRoleMemberLabel": "Guest",
    "M365GroupRoleOwnerLabel": "Owner",
    "M365GroupRoleSectionDescription": "Guest adds the user as a guest member of the Microsoft 365 group — the standard model for externals in Microsoft 365. The guest then gets access to the site and the group resources (Teams, Planner, SharePoint). Choose No role and a SharePoint group below for more limited access.",
    "SPGroupSectionTitle": "SharePoint user group (optional)",
    "SPGroupSectionDescriptionWithGuestRole": "The guest already gets access via the Microsoft 365 group (which is a member of the site members group). Use this only to add the guest to another SharePoint group as well.",
    "SPGroupSectionDescriptionNoRole": "Without the Guest role, the user only gets access to the site through a SharePoint group here — or by sharing content directly with the user later.",
    "SPGroupActionNoneLabel": "Do not add to a SharePoint group",
    "SPGroupActionNoneWithGuestRoleLabel": "Only add to the standard SharePoint members group",
    "SPGroupActionExistingLabel": "Add to an existing group",
    "SPGroupActionNewLabel": "Create a new group",
    "SPGroupExistingPickerLabel": "Choose group",
    "SPGroupExistingPickerPlaceholder": "Pick a SharePoint group …",
    "SPGroupNewNameLabel": "New group name",
    "SPGroupNewNamePlaceholder": "e.g. External collaborators",
    "SPGroupNewPermissionLabel": "Permission level",
    "SPGroupNewNameRequired": "Group name is required",
    "SPPermissionRead": "Read",
    "SPPermissionContribute": "Contribute",
    "SPPermissionEdit": "Edit",
    "SPPermissionFullControl": "Full Control",
    "ColumnM365GroupRole": "M365 role",
    "ColumnSPGroupAction": "SP group action",
    "ColumnSPGroupName": "SP group",
    "ColumnSPPermissionLevel": "Permission level",
    "AccessTitle": "No access",
    "ErrorTitle": "An error occurred",
    "FilterText": "Filter",
    "NotSpecifiedText": "Not specified",
    "BooleanYes": "Yes",
    "BooleanNo": "No",
    "FiltersString": "Filters",
    "Aria": {
      "MenuOverflowCount": "{0} more items",
      "MoveDisabled": "Move disabled",
      "MoveUp": "Move up",
      "MoveUpDisabled": "Move up disabled",
      "MoveDown": "Move down",
      "MoveDownDisabled": "Move down disabled",
      "Back": "Back",
      "Settings": "Settings",
      "Close": "Close"
    },
    "Placeholder": {
      "TextField": "Enter text here",
      "SiteName": "Enter a name for the site",
      "SiteDescription": "Enter a description for the site",
      "Icon": "Enter an icon",
      "ChoiceField": "Select an option",
      "MultiChoiceField": "Select one or more options",
      "GuestField": "Enter guests",
      "UserField": "Enter users",
      "BusinessJustificationField": "Enter a business justification",
      "AdditionalInfoField": "Enter additional information",
      "DatePicker": "Pick a date"
    },
    "Provision": {
      "DrawerSizeFieldLabel": "Drawer size",
      "DrawerSizeMedium": "Standard",
      "DrawerSizeFull": "Fullscreen",
      "FullscreenHeaderTitle": "Provisioning Portal",
      "ChangeTypeButtonLabel": "Change type",
      "DrawerLevel0HeaderText": "Request site",
      "DrawerLevel0DescriptionText": "Here you can request a new site. Choose one of the site types below and fill in the required information.",
      "DrawerLevel1HeaderText": "Classification",
      "DrawerLevel1DescriptionText": "Here you can select classification for the site, activate Teams, sensitivity label, and retention label.",
      "DrawerLevel2HeaderText": "Additional information",
      "DrawerLevel2DescriptionText": "Here you can provide other information for the site, such as site image, language, time zone, and hub connection.",
      "SiteTypeFieldLabel": "Site type",
      "SiteNameFieldLabel": "Site name",
      "SiteNameFieldDescription": "Choose a unique name that follows your organization's naming conventions.",
      "SiteNamePrefixTooltipText": "This is a prefix added to the beginning of the site name.",
      "SiteNameSuffixTooltipText": "This is a suffix added to the end of the site name.",
      "SiteNameValidationErrorMessage": "The name is already taken. Please try a different name.",
      "SiteNameValidationSuccessMessage": "The name is available",
      "SiteDescriptionFieldLabel": "Description",
      "SiteDescriptionFieldDescription": "Providing a description is optional but helps others understand the purpose of your site.",
      "BusinessJustificationFieldLabel": "Business justification",
      "BusinessJustificationFieldDescription": "Why do you need this site? What is the purpose?",
      "AdditionalInfoFieldLabel": "Additional information",
      "AdditionalInfoFieldDescription": "Provide additional information regarding the request.",
      "AliasFieldLabel": "Alias/Name",
      "UrlFieldLabel": "Site address",
      "OwnerFieldLabel": "Owner(s)",
      "OwnerFieldDescription": "Owners have full access and can manage members. You can add more owners later.",
      "MemberFieldLabel": "Member(s)",
      "MemberFieldDescription": "Members have access based on permissions. You can add more members later.",
      "DuplicateOwnerMemberMessage": "A user cannot be both owner and member. Please remove the duplicate(s).",
      "MinimumOwnersMessage": "At least {0} owners are required for this request. Please add more owners.",
      "RequestedByFieldLabel": "Requested on behalf of",
      "RequestedByFieldDescription": "If you're requesting on someone's behalf, enter their name here. Leave blank if it's for yourself.",
      "UserFieldNoOptionsText": "No results...",
      "TeamifyFieldLabel": "Enable Teams for this site?",
      "TeamifyFieldDescription": "If enabled, a Teams workspace will be created and linked to this site.",
      "TeamTemplateFieldLabel": "Teams template",
      "TeamTemplateFieldDescription": "Which Teams template do you want to use for this site?",
      "ConfidentialFieldLabel": "Confidential/Sensitive data",
      "ConfidentialFieldDescription": "Will confidential or sensitive data be stored here? If yes, ensure proper permissions are set.",
      "PrivacyFieldLabel": "Privacy settings",
      "PrivacyFieldDescription": "Set the desired privacy level for the site.",
      "PrivacyFieldOptionPrivate": "Private – Users need permission to join",
      "PrivacyFieldOptionPublic": "Public – Anyone in the organization can join",
      "ExternalSharingFieldLabel": "Allow external guests",
      "ExternalSharingFieldDescription": "If enabled, you can invite and share content (files, folders, libraries, etc.) with external guests. Note: You can only invite guests after the group/site is created.",
      "CommunityNameFieldLabel": "Community name",
      "CommunityNameFieldDescription": "Enter the name for the community",
      "CommunityNameFieldPlaceholder": "Enter community name",
      "CommunityDescriptionFieldLabel": "Community description",
      "CommunityDescriptionFieldDescription": "Enter a description for the community",
      "CommunityDescriptionFieldPlaceholder": "Enter community description",
      "CommunityJustificationFieldLabel": "Community justification",
      "CommunityJustificationFieldDescription": "Provide justification for the community",
      "CommunityJustificationFieldPlaceholder": "Enter community justification",
      "CommunityOwnerFieldLabel": "Community owner(s)",
      "CommunityOwnerFieldDescription": "Select the owner(s) for the community",
      "CommunityOwnerFieldPlaceholder": "Select community owners",
      "CommunityMemberFieldLabel": "Community member(s)",
      "CommunityMemberFieldDescription": "Select the member(s) for the community",
      "CommunityMemberFieldPlaceholder": "Select community members",
      "CommunityPrivacyFieldLabel": "Community privacy",
      "CommunityPrivacyFieldDescription": "Set the privacy level for the community",
      "CommunityPrivacyFieldPlaceholder": "Select privacy level",
      "TeamNameFieldLabel": "Team name",
      "TeamNameFieldDescription": "Enter the name for the team",
      "TeamNameFieldPlaceholder": "Enter team name",
      "TeamDescriptionFieldLabel": "Team description",
      "TeamDescriptionFieldDescription": "Enter a description for the team",
      "TeamDescriptionFieldPlaceholder": "Enter team description",
      "TeamOwnerFieldLabel": "Team owner(s)",
      "TeamOwnerFieldDescription": "Select the owner(s) for the team",
      "TeamOwnerFieldPlaceholder": "Select team owners",
      "TeamMemberFieldLabel": "Team member(s)",
      "TeamMemberFieldDescription": "Select the member(s) for the team",
      "TeamMemberFieldPlaceholder": "Select team members",
      "TeamJustificationFieldLabel": "Team justification",
      "TeamJustificationFieldDescription": "Provide justification for the team",
      "TeamJustificationFieldPlaceholder": "Enter team justification",
      "TeamPrivacyFieldLabel": "Team privacy",
      "TeamPrivacyFieldDescription": "Set the privacy level for the team",
      "TeamPrivacyFieldPlaceholder": "Select privacy level",
      "RenderModeFieldLabel": "Display mode",
      "RenderModeButton": "Button (opens drawer)",
      "RenderModeInline": "Inline form",
      "ButtonLabelFieldLabel": "Button label",
      "ButtonLabelFieldDescription": "Set the label for the button",
      "ParentModeFieldLabel": "Parent mode",
      "ParentModeFieldDescription": "When enabled, the requested area will be linked to the current area as a sub-area. Used for programs/parent areas.",
      "AutoOwnerFieldLabel": "Set current user as owner",
      "AutoOwnerFieldDescription": "Automatically set the current user as owner",
      "AutoOwnerOnText": "Yes",
      "AutoOwnerOffText": "No",
      "AppearanceGroupName": "Appearance",
      "SiteTypeRenderModeFieldLabel": "Site type display mode",
      "SiteTypeRenderModeCardNormal": "Card (with image)",
      "SiteTypeRenderModeCardMinimal": "Card (without image and description)",
      "SiteTypeRenderModeDropdown": "Dropdown",
      "ExpirationDateModeFieldLabel": "Expiration date mode",
      "ExpirationDateModeDate": "Date",
      "ExpirationDateModeMonthDropdown": "Month dropdown",
      "TitlesAndDescriptionsGroupName": "Titles and descriptions",
      "Level0HeaderFieldLabel": "Level 0 title",
      "Level0HeaderFieldDescription": "Set the title for level 0",
      "Level0DescriptionFieldLabel": "Level 0 description",
      "Level0DescriptionFieldDescription": "Set the description for level 0",
      "Level1HeaderFieldLabel": "Level 1 title",
      "Level1HeaderFieldDescription": "Set the title for level 1",
      "Level1DescriptionFieldLabel": "Level 1 description",
      "Level1DescriptionFieldDescription": "Set the description for level 1",
      "Level2HeaderFieldLabel": "Level 2 title",
      "Level2HeaderFieldDescription": "Set the title for level 2",
      "Level2DescriptionFieldLabel": "Level 2 description",
      "Level2DescriptionFieldDescription": "Set the description for level 2",
      "FooterDescriptionFieldLabel": "Footer description",
      "FooterDescriptionFieldDescription": "Set the footer description",
      "ShowHideGroupName": "Show/Hide",
      "HideStatusMenuFieldLabel": "Hide status menu",
      "HideSettingsMenuFieldLabel": "Hide settings menu",
      "ProvisionUrlFieldLabel": "Provision URL",
      "ProvisionUrlFieldDescription": "URL of the site handling provisioning requests. When empty, the tenant registry (storage entity bp_ProvisionUrls) is used, then /sites/bestillingsportalen.",
      "FieldsConfigurationLabel": "Fields configuration",
      "FieldsConfigurationPanelHeader": "Fields configuration panel",
      "FieldsConfigurationManageBtnLabel": "Manage fields configuration",
      "FieldOrderLabel": "Default order",
      "FieldNameLabel": "Field name (internal)",
      "FieldDisplayNameLabel": "Display name",
      "FieldDescriptionLabel": "Field description",
      "FieldPlaceholderLabel": "Field placeholder",
      "FieldDataTypeLabel": "Field data type",
      "FieldDataTypeText": "Text",
      "FieldDataTypeNote": "Note",
      "FieldDataTypeNumber": "Number",
      "FieldDataTypeChoice": "Choice",
      "FieldDataTypeUserMulti": "Multiple users",
      "FieldDataTypeGuest": "Guest",
      "FieldDataTypeDate": "Date",
      "FieldDataTypeTags": "Tags",
      "FieldDataTypeBoolean": "Boolean",
      "FieldDataTypePercentage": "Percentage",
      "FieldDataTypeSite": "Site",
      "FieldDataTypeImage": "Image",
      "FieldRequiredLabel": "Field required",
      "FieldHiddenLabel": "Field hidden",
      "FieldLevelLabel": "Field level",
      "WebPartDescription": "Web part description",
      "MissingFieldsTitle": "Missing required fields",
      "GuestFieldLabel": "Guest(s)",
      "GuestFieldDescription": "Guests have limited access. You can add more guests later. Please enter a valid email address.",
      "GuestFieldNoOptionsText": "Cannot add...",
      "SensitivityLabelFieldLabel": "Sensitivity label",
      "SensitivityLabelFieldDescription": "Which sensitivity label do you want to apply to this site?",
      "RetentionLabelFieldLabel": "Retention label",
      "RetentionLabelFieldDescription": "Which retention label do you want to apply to this site?",
      "ExpirationDateFieldLabel": "Expiration date",
      "ExpirationDateFieldDescription": "When should the site expire? Note: The site will not be deleted automatically after this date.",
      "ReadOnlyGroupFieldLabel": "Enable read-only access group",
      "ReadOnlyGroupFieldDescription": "Enable a read-only group for the site. Members of this group will have read-only access.",
      "InternalChannelFieldLabel": "Enable internal channel",
      "InternalChannelFieldDescription": "When enabled, an internal channel will be created in Teams.",
      "LanguageFieldLabel": "Language",
      "TimeZoneFieldLabel": "Time zone",
      "DefaultLanguage": "English (United States)",
      "DefaultTimeZone": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
      "HubSiteFieldLabel": "Hub association",
      "DefaultHubInfoMessage": "This site will be associated with the hub site: {0}",
      "DefaultHubResolveErrorMessage": "The default hub configured for this site type could not be resolved. The site will be associated with {0} instead.",
      "ParentSiteFieldLabel": "Parent site",
      "ParentSiteFieldDescription": "This sub-area will be linked to the parent site shown here.",
      "ImageFieldLabel": "Set site image",
      "ImageFieldDescription": "Upload an image to use as the site image.",
      "ImageDropZoneText": "Drag and drop image here, or click to select a file (png, jpeg/jpg)",
      "DrawerFooterDescriptionText": "Your site will be linked to a Microsoft 365 Group, which provides a shared OneNote notebook, group email address, and shared calendar.",
      "ProjectDataPreviewText": "This information will be applied to the project properties when the configuration wizard runs",
      "PreviousButtonLabel": "Previous",
      "NextButtonLabel": "Next",
      "ProvisionButtonLabel": "Request site",
      "ToastCreatedTitle": "Site requested",
      "ToastCreatedBody": "The site has been requested and is being processed.",
      "ToastCreatedErrorTitle": "Request error",
      "ToastCreatedErrorBody": "An error occurred while requesting the site. Please try again or contact an administrator.",
      "StatusMenuLabel": "My requests",
      "SettingsMenuLabel": "Settings",
      "SettingsSearchLabel": "Search settings",
      "SettingsDialogTitle": "Provisioning Portal Settings",
      "SettingsDialogDescription": "Here you can see all settings for the provisioning portal.",
      "SettingsDialogSpinnerLabel": "Updating and retrieving settings...",
      "SettingsDialogNoSearchResultsLabel": "No settings match your search.",
      "SettingsDialogNoResultsLabel": "There are no settings for the provisioning portal.",
      "SettingLabel": "Setting",
      "DescriptionLabel": "Description",
      "ValueLabel": "Value",
      "EditLabel": "Edit",
      "StatusSearchLabel": "Search requests",
      "UpdateLabel": "Update",
      "StatusDialogTitle": "My requests",
      "StatusDialogDescription": "View the status of your site requests, including type, status, and submission date. You can also delete unsubmitted or rejected requests.",
      "StatusDialogSpinnerLabel": "Updating and retrieving requests...",
      "StatusDialogNoSearchResultsLabel": "No requests match your search.",
      "StatusDialogNoResultsLabel": "You have no site requests. Submit a new one to track its status here.",
      "StatusLabel": "Status",
      "SubmittedLabel": "Submitted",
      "ApprovedLabel": "Approved",
      "RejectedLabel": "Rejected",
      "PendingApprovalLabel": "Pending approval",
      "SpaceCreationFailedLabel": "Site creation failed",
      "SpaceAlreadyExistsLabel": "Site already exists",
      "TeamRequestedLabel": "Team requested",
      "SpaceCreationLabel": "Creating site",
      "SpaceCreatedLabel": "Site created",
      "NotSubmittedLabel": "Not submitted",
      "SubmittedDateLabel": "Submission date",
      "DeleteLabel": "Delete",
      "DeleteSubmissionLabel": "Delete request",
      "DeleteSubmissionConfirmationLabel": "Are you sure you want to delete this request?",
      "DeletedSubmissionToastTitle": "Request deleted",
      "DeletedSubmissionToastBody": "The request, {0}, has been deleted.",
      "DeletedSubmissionErrorToastTitle": "Deletion error",
      "DeletedSubmissionErrorToastBody": "An error occurred while deleting the request. Please try again or contact an administrator.",
      "NoHubSiteConnectionMessage": "Hub site association is not available. The site can be requested, but will not be connected to a hub.",
      "RequestedSource": "Project Portal – Request form",
      "SensitivityLabelLibraryFieldLabel": "Sensitivity label for library",
      "SensitivityLabelLibraryFieldDescription": "Which sensitivity label do you want to apply to the document library for this site?",
      "ImageDropZoneErrorText": "The image could not be uploaded. Please ensure the file is an image (png, jpeg/jpg) and does not exceed 512 KB.",
      "ExpirationDateNoneOption": "No expiration date",
      "ExpirationDateMonthOption": "{0} month(s)",
      "NoProvisionAccessMessage": "You do not have access to the Provisioning Portal.",
      "SiteNotFoundTitle": "Provisioning Portal not found",
      "SiteNotFoundMessage": "The Provisioning Portal was not found at {0}. Verify that the URL is configured correctly, or contact your administrator.",
      "InstancePickerTitle": "Choose provisioning portal",
      "InstancePickerDescription": "You have access to multiple provisioning portals. Choose which one to use. Your choice is remembered.",
      "SwitchInstanceLabel": "Switch provisioning portal",
      "CurrentInstanceLabel": "Active provisioning portal: {0}",
      "ToastUserResolveErrorTitle": "People could not be added",
      "ToastUserResolveErrorBody": "One or more selected people could not be attached to the request. Search for the person again, or contact an administrator.",
      "DefaultTeamTemplate": "Standard",
      "ConfirmationTitle": "Request received!",
      "ConfirmationMessage": "Your request has been received and will be processed. You will receive a notification when your site is ready.",
      "NewRequestButton": "New request",
      "ViewRequestsButton": "My requests",
      "ConfigEditorButton": "Web part settings",
      "ConfigEditorTitle": "Web part configuration",
      "ConfigEditorDescription": "Edit the web part configuration in JSON format. Changes will be saved to TeamsAppConfig.json and applied when you refresh the app.",
      "ConfigJsonLabel": "Configuration (JSON)",
      "ConfigJsonHint": "Edit the JSON configuration. Make sure the JSON is valid before saving.",
      "ConfigSaveButton": "Save configuration",
      "ConfigSavingButton": "Saving...",
      "ConfigResetButton": "Reset",
      "ConfigResetConfirmationLabel": "Are you sure you want to reset the configuration?",
      "ConfigSaveSuccess": "Configuration saved. Refreshing...",
      "ConfigSaveSuccessTitle": "Success",
      "ConfigSaveError": "Could not save configuration",
      "ConfigInvalidJson": "Invalid JSON format. Please check the syntax.",
      "ConfigEditorAccessDenied": "You must be a site administrator to edit the configuration.",
      "NotConfiguredTitle": "Not configured",
      "NotConfiguredText": "The provisioning portal URL has not been configured. Please set this in the web part properties.",
      "RequireProvisionAccessFieldLabel": "Require access to provisioning portal",
      "TypeConfigurationLabel": "Type configuration",
      "TypeConfigurationPanelHeader": "Type configuration",
      "TypeConfigurationManageBtnLabel": "Configure types",
      "TypeNameLabel": "Type",
      "HiddenFieldsForTypeLabel": "Hidden fields for this type",
      "HiddenFieldsForTypePlaceholder": "Select fields to hide...",
      "RequiredFieldsForTypeLabel": "Required fields for this type",
      "RequiredFieldsForTypePlaceholder": "Select fields to be required...",
      "FieldConfigurationJsonLabel": "Field configuration (JSON)",
      "FieldConfigurationJsonPlaceholder": "Enter field configuration in JSON format.",
      "PropertyEditorLabel": "Edit web part properties (JSON)",
      "PropertyEditorDescription": "Here you can edit the web part properties in JSON format. Export and import of properties is also possible so that settings can be reused and imported in other web parts.",
      "DebugModeLabel": "DebugMode",
      "DebugModeOnText": "On",
      "DebugModeOffText": "Off",
      "ProvisionError": "Could not retrieve data from the list '{0}', please check that the web part is correctly configured and that the list exists on the Provisioning Portal. Error: {1}",
      "StandardTeamTemplate": "Standard team template",
      "FieldLogicGroupName": "Field logic",
      "DefaultExpirationDateFieldLabel": "Default expiration date",
      "ShowTeamTemplateFieldLabel": "Show Teams template field",
      "ReadOnlyGroupLogicFieldLabel": "Require read-only group for internal channel",
      "ProjectAreaType": "Project area",
      "VivaEngageCommunityType": "Viva Engage Community",
      "MicrosoftTeamsTeamType": "Microsoft Teams Team",
      "ExcludedTypesFieldLabel": "Excluded site types",
      "ExcludedTypesFieldDescription": "Select site types that should be hidden from users in this web part.",
      "ProvisionAccessGroupTitleFieldLabel": "Access group title",
      "ProvisionAccessGroupTitleFieldDescription": "Title of the SharePoint group on the current site that grants access to the provisioning portal. Defaults to \"Bestillingsportalen\".",
      "AdvancedGroupName": "Advanced"
    }
  }
})
