declare interface IProvisionWebPartsStrings {
  PropertyPaneDescription: string
  BasicGroupName: string
  GeneralGroupName: string
  InviteSettingsGroupName: string
  PerGuestGroupName: string
  DefaultsGroupName: string
  ShowHideGroupName: string
  DrawerShowHideGroupName: string
  StatusShowHideGroupName: string
  AdvancedGroupName: string
  BooleanOn: string
  BooleanOff: string
  DefaultM365GroupRoleFieldLabel: string
  DefaultM365GroupRoleFieldDescription: string
  DefaultSpGroupActionFieldLabel: string
  DefaultSpGroupActionFieldDescription: string
  DefaultSpGroupNameFieldLabel: string
  DefaultSpGroupNameFieldDescription: string
  PresetSpGroupNameFieldLabel: string
  PresetSpGroupNameFieldDescription: string
  SPGroupActionPresetTemplate: string
  SPGroupActionPresetLabel: string
  SpGroupOptionsGroupName: string
  ShowSpActionNoneFieldLabel: string
  ShowSpActionExistingFieldLabel: string
  ShowSpActionNewFieldLabel: string
  ShowSpActionPresetFieldLabel: string
  SpGroupActionOrderFieldLabel: string
  SpGroupActionOrderFieldDescription: string
  DefaultSpPermissionLevelFieldLabel: string
  DefaultSpPermissionLevelFieldDescription: string
  AutoSelectVisitorGroupFieldLabel: string
  AutoSelectVisitorGroupFieldDescription: string
  LockM365GroupRoleFieldLabel: string
  LockM365GroupRoleFieldDescription: string
  LockSpGroupActionFieldLabel: string
  LockSpGroupActionFieldDescription: string
  LockedRoleLabel: string
  LockedActionLabel: string
  LockedGroupNameLabel: string
  LockedFieldTooltip: string
  ShowAccessPreviewFieldLabel: string
  ShowStatusSummaryFieldLabel: string
  ShowCopyRedeemUrlFieldLabel: string
  ShowRetryButtonFieldLabel: string
  ShowColumnM365RoleFieldLabel: string
  ShowColumnSPGroupActionFieldLabel: string
  ShowColumnSPGroupNameFieldLabel: string
  ShowColumnSPPermissionLevelFieldLabel: string
  ShowM365GroupRoleSectionFieldLabel: string
  ShowSPGroupSectionFieldLabel: string
  TitleFieldLabel: string
  TitleFieldDescription: string
  DescriptionFieldDescription: string
  DisplayModeFieldDescription: string
  InviteModeFieldDescription: string
  InviteAccessLevelFieldDescription: string
  ShowSpActionsDescription: string
  ShowAccessPreviewFieldDescription: string
  ShowM365GroupRoleSectionFieldDescription: string
  ShowSPGroupSectionFieldDescription: string
  ShowStatusSummaryFieldDescription: string
  ShowCopyRedeemUrlFieldDescription: string
  ShowRetryButtonFieldDescription: string
  StatusColumnsDescription: string
  PerGuestProfileModeFieldDescription: string
  PerGuestRoleModeFieldDescription: string
  DescriptionFieldLabel: string
  WebPartTitleInfoLabelTitle: string
  DisplayModeFieldLabel: string
  DisplayModeInlineLabel: string
  DisplayModeDialogLabel: string
  InviteModeFieldLabel: string
  InviteModeSingleLabel: string
  InviteModeMultiLabel: string
  InviteAccessLevelFieldLabel: string
  InviteAccessLevelOwnerLabel: string
  InviteAccessLevelMemberLabel: string
  InviteAccessLevelAnyoneLabel: string
  PerGuestProfileModeFieldLabel: string
  PerGuestRoleModeFieldLabel: string
  FeatureModeDisabledLabel: string
  FeatureModeOptionalLabel: string
  FeatureModeEnforcedLabel: string
  PerGuestProfileLabel: string
  PerGuestRoleLabel: string
  ViewSettingsLabel: string
  ViewStatusButton: string
  StatusDialogTitle: string
  StatusSummaryTotal: string
  StatusSummaryPending: string
  StatusSummaryFailed: string
  CloseButton: string
  GuestRequestListTitleFieldLabel: string
  GuestRequestListTitleFieldDescription: string
  GuestRequestSiteUrlFieldLabel: string
  GuestRequestSiteUrlFieldDescription: string
  HiddenSpGroupsFieldLabel: string
  HiddenSpGroupsFieldDescription: string
  AllowedSpGroupsFieldLabel: string
  AllowedSpGroupsFieldDescription: string

  InviteButton: string
  InviteDrawerHeader: string
  InviteDrawerDescription: string
  GuestPickerLabel: string
  GuestPickerPlaceholder: string
  GuestPickerInvalidEmail: string
  GuestPickerNoOptionsText: string
  GuestPickerHelperText: string
  FirstNameLabel: string
  FirstNameDescription: string
  LastNameLabel: string
  LastNameDescription: string
  CompanyLabel: string
  CompanyDescription: string
  GuestExistsBadge: string
  GuestExistsMissingDetails: string
  NoValuePlaceholder: string
  AccessPreviewTitle: string
  AccessNoM365: string
  AccessNoSiteAccessWarning: string
  AccessSiteEdit: string
  AccessTeamsMember: string
  AccessOneNotePlannerCalendar: string
  AccessNotGroupConnectedNote: string
  AccessSpGroupAddTemplate: string
  AccessSpGroupCreateTemplate: string
  CancelButton: string
  ClearFieldLabel: string
  SendInvitationsButton: string
  RefreshButton: string
  RetryButton: string

  StatusHeader: string
  StatusEmpty: string
  StatusSearchPlaceholder: string
  StatusDialogDescription: string
  StatusDialogNoResultsLabel: string
  StatusDialogNoSearchResultsLabel: string
  StatusDialogSpinnerLabel: string

  ColumnEmail: string
  ColumnStatus: string
  ColumnRequestedBy: string
  ColumnCreated: string
  ColumnError: string
  CopyRedeemUrlLabel: string
  CopyRedeemUrlCopied: string

  StatusPending: string
  StatusInvited: string
  StatusFailed: string

  ToastSuccessTitle: string
  ToastSuccessBody: string
  ToastErrorTitle: string
  ToastErrorBody: string

  M365GroupSectionTitle: string
  M365GroupRoleNoneLabel: string
  M365GroupRoleVisitorLabel: string
  M365GroupRoleMemberLabel: string
  M365GroupRoleOwnerLabel: string
  M365GroupRoleSectionDescription: string

  SPGroupSectionTitle: string
  SPGroupSectionDescriptionWithGuestRole: string
  SPGroupSectionDescriptionNoRole: string
  SPGroupActionNoneLabel: string
  SPGroupActionNoneWithGuestRoleLabel: string
  SPGroupActionExistingLabel: string
  SPGroupActionNewLabel: string
  SPGroupExistingPickerLabel: string
  SPGroupExistingPickerPlaceholder: string
  SPGroupNewNameLabel: string
  SPGroupNewNamePlaceholder: string
  SPGroupNewPermissionLabel: string
  SPGroupNewNameRequired: string

  SPPermissionRead: string
  SPPermissionContribute: string
  SPPermissionEdit: string
  SPPermissionFullControl: string

  ColumnM365GroupRole: string
  ColumnSPGroupAction: string
  ColumnSPGroupName: string
  ColumnSPPermissionLevel: string

  AccessTitle: string
  ErrorTitle: string
  FilterText: string
  NotSpecifiedText: string
  BooleanYes: string
  BooleanNo: string
  FiltersString: string
  Aria: {
    MenuOverflowCount: string
    MoveDisabled: string
    MoveUp: string
    MoveUpDisabled: string
    MoveDown: string
    MoveDownDisabled: string
    Back: string
    Settings: string
    Close: string
  }
  Placeholder: {
    TextField: string
    SiteName: string
    SiteDescription: string
    Icon: string
    ChoiceField: string
    MultiChoiceField: string
    GuestField: string
    UserField: string
    BusinessJustificationField: string
    AdditionalInfoField: string
    DatePicker: string
  }
  Provision: {
    DrawerSizeFieldLabel: string
    DrawerSizeMedium: string
    DrawerSizeFull: string
    FullscreenHeaderTitle: string
    ChangeTypeButtonLabel: string
    DrawerLevel0HeaderText: string
    DrawerLevel0DescriptionText: string
    DrawerLevel1HeaderText: string
    DrawerLevel1DescriptionText: string
    DrawerLevel2HeaderText: string
    DrawerLevel2DescriptionText: string
    SiteTypeFieldLabel: string
    SiteNameFieldLabel: string
    SiteNameFieldDescription: string
    SiteNamePrefixTooltipText: string
    SiteNameSuffixTooltipText: string
    SiteNameValidationErrorMessage: string
    SiteNameRequestExistsErrorMessage: string
    SiteNameValidationSuccessMessage: string
    SiteDescriptionFieldLabel: string
    SiteDescriptionFieldDescription: string
    BusinessJustificationFieldLabel: string
    BusinessJustificationFieldDescription: string
    AdditionalInfoFieldLabel: string
    AdditionalInfoFieldDescription: string
    AliasFieldLabel: string
    UrlFieldLabel: string
    OwnerFieldLabel: string
    OwnerFieldDescription: string
    MemberFieldLabel: string
    MemberFieldDescription: string
    DuplicateOwnerMemberMessage: string
    MinimumOwnersMessage: string
    RequestedByFieldLabel: string
    RequestedByFieldDescription: string
    UserFieldNoOptionsText: string
    TeamifyFieldLabel: string
    TeamifyFieldDescription: string
    TeamTemplateFieldLabel: string
    TeamTemplateFieldDescription: string
    ConfidentialFieldLabel: string
    ConfidentialFieldDescription: string
    PrivacyFieldLabel: string
    PrivacyFieldDescription: string
    PrivacyFieldOptionPrivate: string
    PrivacyFieldOptionPublic: string
    ExternalSharingFieldLabel: string
    ExternalSharingFieldDescription: string
    GuestFieldLabel: string
    GuestFieldDescription: string
    GuestFieldNoOptionsText: string
    SensitivityLabelFieldLabel: string
    SensitivityLabelFieldDescription: string
    SensitivityLabelLibraryFieldLabel: string
    SensitivityLabelLibraryFieldDescription: string
    RetentionLabelFieldLabel: string
    RetentionLabelFieldDescription: string
    ExpirationDateFieldLabel: string
    ExpirationDateFieldDescription: string
    ReadOnlyGroupFieldLabel: string
    ReadOnlyGroupFieldDescription: string
    InternalChannelFieldLabel: string
    InternalChannelFieldDescription: string
    LanguageFieldLabel: string
    TimeZoneFieldLabel: string
    HubSiteFieldLabel: string
    DefaultHubInfoMessage: string
    DefaultHubResolveErrorMessage: string
    ParentSiteFieldLabel: string
    ParentSiteFieldDescription: string
    ImageFieldLabel: string
    ImageFieldDescription: string
    ImageDropZoneText: string
    ImageDropZoneErrorText: string
    DrawerFooterDescriptionText: string
    ProjectDataPreviewText: string
    PreviousButtonLabel: string
    NextButtonLabel: string
    ProvisionButtonLabel: string
    ToastCreatedTitle: string
    ToastCreatedBody: string
    ToastCreatedErrorTitle: string
    ToastCreatedErrorBody: string
    StatusMenuLabel: string
    SettingsMenuLabel: string
    SettingsSearchLabel: string
    SettingsDialogTitle: string
    SettingsDialogDescription: string
    SettingsDialogSpinnerLabel: string
    SettingsDialogNoSearchResultsLabel: string
    SettingsDialogNoResultsLabel: string
    SettingLabel: string
    DescriptionLabel: string
    ValueLabel: string
    EditLabel: string
    StatusSearchLabel: string
    UpdateLabel: string
    StatusDialogTitle: string
    StatusDialogDescription: string
    StatusDialogSpinnerLabel: string
    StatusDialogNoSearchResultsLabel: string
    StatusDialogNoResultsLabel: string
    StatusLabel: string
    SubmittedLabel: string
    ApprovedLabel: string
    RejectedLabel: string
    PendingApprovalLabel: string
    SpaceCreationFailedLabel: string
    SpaceAlreadyExistsLabel: string
    TeamRequestedLabel: string
    SpaceCreationLabel: string
    SpaceCreatedLabel: string
    NotSubmittedLabel: string
    SubmittedDateLabel: string
    DeleteLabel: string
    DeleteSubmissionLabel: string
    DeleteSubmissionConfirmationLabel: string
    DeletedSubmissionToastTitle: string
    DeletedSubmissionToastBody: string
    DeletedSubmissionErrorToastTitle: string
    DeletedSubmissionErrorToastBody: string
    RequestedSource: string
    NotConfiguredTitle: string
    NotConfiguredText: string
    ExpirationDateNoneOption: string
    ExpirationDateMonthOption: string
    NoProvisionAccessMessage: string
    SiteNotFoundTitle: string
    SiteNotFoundMessage: string
    InstancePickerTitle: string
    InstancePickerDescription: string
    SwitchInstanceLabel: string
    CurrentInstanceLabel: string
    ToastNameConflictErrorTitle: string
    ToastNameConflictErrorBody: string
    ToastUserResolveErrorTitle: string
    ToastUserResolveErrorBody: string
    NoHubSiteConnectionMessage: string
    DefaultTeamTemplate: string
    DefaultLanguage: string
    DefaultTimeZone: string
    ConfirmationTitle: string
    ConfirmationMessage: string
    NewRequestButton: string
    ViewRequestsButton: string
    ConfigEditorButton: string
    ConfigEditorTitle: string
    ConfigEditorDescription: string
    ConfigJsonLabel: string
    ConfigJsonHint: string
    ConfigSaveButton: string
    ConfigSavingButton: string
    ConfigResetButton: string
    ConfigResetConfirmationLabel: string
    ConfigSaveSuccess: string
    ConfigSaveSuccessTitle: string
    ConfigSaveError: string
    ConfigInvalidJson: string
    ConfigEditorAccessDenied: string
    CommunityNameFieldLabel: string
    CommunityNameFieldDescription: string
    CommunityNameFieldPlaceholder: string
    CommunityDescriptionFieldLabel: string
    CommunityDescriptionFieldDescription: string
    CommunityDescriptionFieldPlaceholder: string
    CommunityJustificationFieldLabel: string
    CommunityJustificationFieldDescription: string
    CommunityJustificationFieldPlaceholder: string
    CommunityOwnerFieldLabel: string
    CommunityOwnerFieldDescription: string
    CommunityOwnerFieldPlaceholder: string
    CommunityMemberFieldLabel: string
    CommunityMemberFieldDescription: string
    CommunityMemberFieldPlaceholder: string
    CommunityPrivacyFieldLabel: string
    CommunityPrivacyFieldDescription: string
    CommunityPrivacyFieldPlaceholder: string
    TeamNameFieldLabel: string
    TeamNameFieldDescription: string
    TeamNameFieldPlaceholder: string
    TeamDescriptionFieldLabel: string
    TeamDescriptionFieldDescription: string
    TeamDescriptionFieldPlaceholder: string
    TeamOwnerFieldLabel: string
    TeamOwnerFieldDescription: string
    TeamOwnerFieldPlaceholder: string
    TeamMemberFieldLabel: string
    TeamMemberFieldDescription: string
    TeamMemberFieldPlaceholder: string
    TeamJustificationFieldLabel: string
    TeamJustificationFieldDescription: string
    TeamJustificationFieldPlaceholder: string
    TeamPrivacyFieldLabel: string
    TeamPrivacyFieldDescription: string
    TeamPrivacyFieldPlaceholder: string
    RenderModeFieldLabel: string
    RenderModeButton: string
    RenderModeInline: string
    ButtonLabelFieldLabel: string
    ButtonLabelFieldDescription: string
    ParentModeFieldLabel: string
    ParentModeFieldDescription: string
    AutoOwnerFieldLabel: string
    AutoOwnerFieldDescription: string
    AutoOwnerOnText: string
    AutoOwnerOffText: string
    AppearanceGroupName: string
    SiteTypeRenderModeFieldLabel: string
    SiteTypeRenderModeCardNormal: string
    SiteTypeRenderModeCardMinimal: string
    SiteTypeRenderModeDropdown: string
    ExpirationDateModeFieldLabel: string
    ExpirationDateModeDate: string
    ExpirationDateModeMonthDropdown: string
    TitlesAndDescriptionsGroupName: string
    Level0HeaderFieldLabel: string
    Level0HeaderFieldDescription: string
    Level0DescriptionFieldLabel: string
    Level0DescriptionFieldDescription: string
    Level1HeaderFieldLabel: string
    Level1HeaderFieldDescription: string
    Level1DescriptionFieldLabel: string
    Level1DescriptionFieldDescription: string
    Level2HeaderFieldLabel: string
    Level2HeaderFieldDescription: string
    Level2DescriptionFieldLabel: string
    Level2DescriptionFieldDescription: string
    FooterDescriptionFieldLabel: string
    FooterDescriptionFieldDescription: string
    ShowHideGroupName: string
    RequireProvisionAccessFieldLabel: string
    HideStatusMenuFieldLabel: string
    HideSettingsMenuFieldLabel: string
    AdvancedGroupName: string
    ProvisionUrlFieldLabel: string
    ProvisionUrlFieldDescription: string
    FieldsConfigurationLabel: string
    FieldsConfigurationPanelHeader: string
    FieldsConfigurationManageBtnLabel: string
    FieldOrderLabel: string
    FieldNameLabel: string
    FieldDisplayNameLabel: string
    FieldDescriptionLabel: string
    FieldPlaceholderLabel: string
    FieldDataTypeLabel: string
    FieldDataTypeText: string
    FieldDataTypeNote: string
    FieldDataTypeNumber: string
    FieldDataTypeChoice: string
    FieldDataTypeUserMulti: string
    FieldDataTypeGuest: string
    FieldDataTypeDate: string
    FieldDataTypeTags: string
    FieldDataTypeBoolean: string
    FieldDataTypePercentage: string
    FieldDataTypeSite: string
    FieldDataTypeImage: string
    FieldRequiredLabel: string
    FieldHiddenLabel: string
    FieldLevelLabel: string
    TypeConfigurationLabel: string
    TypeConfigurationPanelHeader: string
    TypeConfigurationManageBtnLabel: string
    TypeNameLabel: string
    HiddenFieldsForTypeLabel: string
    HiddenFieldsForTypePlaceholder: string
    RequiredFieldsForTypeLabel: string
    RequiredFieldsForTypePlaceholder: string
    FieldConfigurationJsonLabel: string
    FieldConfigurationJsonPlaceholder: string
    PropertyEditorLabel: string
    PropertyEditorDescription: string
    DebugModeLabel: string
    DebugModeOnText: string
    DebugModeOffText: string
    WebPartDescription: string
    MissingFieldsTitle: string
    ProvisionError: string
    StandardTeamTemplate: string
    FieldLogicGroupName: string
    DefaultExpirationDateFieldLabel: string
    ShowTeamTemplateFieldLabel: string
    ReadOnlyGroupLogicFieldLabel: string
    ProjectAreaType: string
    VivaEngageCommunityType: string
    MicrosoftTeamsTeamType: string
    ExcludedTypesFieldLabel: string
    ExcludedTypesFieldDescription: string
    ProvisionAccessGroupTitleFieldLabel: string
    ProvisionAccessGroupTitleFieldDescription: string
  }
}

declare module 'ProvisionWebPartsStrings' {
  const strings: IProvisionWebPartsStrings
  export = strings
}
