define([], function () {
  return {
    "PropertyPaneDescription": "Innstillinger for webdelen Inviter gjester.",
    "BasicGroupName": "Generelt",
    "GeneralGroupName": "Generelt",
    "InviteSettingsGroupName": "Invitasjonsoppsett",
    "PerGuestGroupName": "Funksjoner per gjest",
    "DefaultsGroupName": "Standardverdier",
    "ShowHideGroupName": "Vis/Skjul",
    "DrawerShowHideGroupName": "Vis/Skjul i invitasjons-drawer",
    "StatusShowHideGroupName": "Vis/Skjul i invitasjonsstatus",
    "AdvancedGroupName": "Avansert",
    "BooleanOn": "På",
    "BooleanOff": "Av",
    "DefaultM365GroupRoleFieldLabel": "Standard M365-rolle",
    "DefaultM365GroupRoleFieldDescription": "Forhåndsvalgt rolle når invite-drawer åpnes. Gjest = gjestemedlem i Microsoft 365-gruppen (standard gjestetilgang i Microsoft 365); eksterne kan aldri bli eiere.",
    "DefaultSpGroupActionFieldLabel": "Standard SP-gruppehandling",
    "DefaultSpGroupActionFieldDescription": "Forhåndsvalgt handling for SharePoint-brukergruppe. Standard er «Ikke legg til» — rollen Gjest gir allerede tilgang via M365-gruppen. «Legg til i eksisterende» vil pre-velge sitens Besøkende-gruppe (se også Auto-velg Besøkende-gruppe).",
    "DefaultSpGroupNameFieldLabel": "Standard SP-gruppenavn",
    "DefaultSpGroupNameFieldDescription": "Navn på en spesifikk SharePoint-gruppe som skal forhåndsvelges når «Legg til i eksisterende» er valgt. Hvis tomt brukes Besøkende-gruppen (når Auto-velg er på). Gruppen må eksistere på området.",
    "PresetSpGroupNameFieldLabel": "Forhåndsvalgt SP-gruppe",
    "PresetSpGroupNameFieldDescription": "Navn på en SharePoint-gruppe. Hvis utfylt vises et fjerde valg i drawer som legger gjesten i akkurat denne gruppen — uten dropdown. Tomt = valget skjules. Gruppen må eksistere på området.",
    "SPGroupActionPresetTemplate": "Legg til i «{0}»",
    "SPGroupActionPresetLabel": "Forhåndsvalgt gruppe",
    "SpGroupOptionsGroupName": "SharePoint-gruppevalg",
    "ShowSpActionNoneFieldLabel": "Vis valg: Ikke legg til",
    "ShowSpActionExistingFieldLabel": "Vis valg: Legg til i eksisterende",
    "ShowSpActionNewFieldLabel": "Vis valg: Opprett ny gruppe",
    "ShowSpActionPresetFieldLabel": "Vis valg: Forhåndsvalgt gruppe",
    "ShowSpActionsDescription": "Bryterne over styrer hvilke SP-gruppevalg som vises i invitasjons-draweren. Er alle av, vises kun «Ikke legg til». «Forhåndsvalgt gruppe» krever i tillegg at Forhåndsvalgt SP-gruppe er satt under Standardverdier.",
    "SpGroupActionOrderFieldLabel": "Rekkefølge på valg",
    "SpGroupActionOrderFieldDescription": "Dra for å endre rekkefølgen på SP-gruppevalgene i drawer. Synlighet styres av bryterne over.",
    "DefaultSpPermissionLevelFieldLabel": "Standard tilgangsnivå",
    "DefaultSpPermissionLevelFieldDescription": "Forhåndsvalgt tilgangsnivå når «Opprett ny gruppe» er valgt. Brukes kun når standard SP-gruppehandling = Opprett ny gruppe.",
    "AutoSelectVisitorGroupFieldLabel": "Auto-velg Besøkende-gruppe",
    "AutoSelectVisitorGroupFieldDescription": "Forhåndsvelger sitens Besøkende-gruppe når drawer åpnes (gjelder kun når standard SP-gruppehandling = Legg til i eksisterende).",
    "LockM365GroupRoleFieldLabel": "Lås standard M365-rolle",
    "LockM365GroupRoleFieldDescription": "Skjul rolle-valgene i drawer slik at brukeren kun ser standard-rollen (kan ikke endres).",
    "LockSpGroupActionFieldLabel": "Lås standard SP-gruppehandling",
    "LockSpGroupActionFieldDescription": "Skjul SP-gruppehandling-valgene i drawer slik at brukeren kun ser standard-handlingen (kan ikke endres). Underliggende felter (gruppevalg, nytt gruppenavn, tilgangsnivå) forblir tilgjengelige.",
    "LockedRoleLabel": "Rolle: {0}",
    "LockedActionLabel": "Handling: {0}",
    "LockedGroupNameLabel": "Gruppe: {0}",
    "LockedFieldTooltip": "Låst av administrator — kan ikke endres.",
    "ShowAccessPreviewFieldLabel": "Vis tilgangs-forhåndsvisning i drawer",
    "ShowAccessPreviewFieldDescription": "Viser boksen «Tilgang gjesten får» i draweren — en oppsummering av hva de valgte innstillingene faktisk gir gjesten tilgang til.",
    "ShowStatusSummaryFieldLabel": "Vis statussammendrag (totalt/venter/feilet)",
    "ShowStatusSummaryFieldDescription": "Viser tellere for totalt/venter/feilet ved siden av knappen som åpner statuslisten. Gjelder kun kompakt visning (dialog).",
    "ShowCopyRedeemUrlFieldLabel": "Vis Kopier-invitasjonslenke-knapp",
    "ShowCopyRedeemUrlFieldDescription": "Viser en knapp i statuslisten som kopierer gjestens innløsningslenke — nyttig hvis invitasjons-e-posten ikke nådde frem.",
    "ShowRetryButtonFieldLabel": "Vis Prøv-på-nytt-knapp",
    "ShowRetryButtonFieldDescription": "Viser «Prøv på nytt» på feilede invitasjoner. Oppretter en ny forespørsel med samme verdier og legger den feilede i papirkurven.",
    "ShowColumnM365RoleFieldLabel": "Vis kolonne: M365-rolle",
    "ShowColumnSPGroupActionFieldLabel": "Vis kolonne: SP-gruppehandling",
    "ShowColumnSPGroupNameFieldLabel": "Vis kolonne: SP-gruppe",
    "StatusColumnsDescription": "Kolonne-bryterne styrer hvilke detaljer som vises per invitasjon i statuslisten, i tillegg til gjest, status og dato.",
    "ShowColumnSPPermissionLevelFieldLabel": "Vis kolonne: Tilgangsnivå",
    "ShowM365GroupRoleSectionFieldLabel": "Vis seksjon: Rolle på området",
    "ShowM365GroupRoleSectionFieldDescription": "Viser rolleseksjonen i draweren. Skjult = standard-rollen brukes for alle invitasjoner uten at avsenderen ser eller kan endre den.",
    "ShowSPGroupSectionFieldLabel": "Vis seksjon: SharePoint-brukergruppe",
    "ShowSPGroupSectionFieldDescription": "Viser SP-gruppeseksjonen i draweren. Skjult = standard SP-gruppehandling brukes for alle invitasjoner.",
    "TitleFieldLabel": "Tittel",
    "TitleFieldDescription": "Overskriften som vises øverst i webdelen.",
    "DescriptionFieldLabel": "Beskrivelse",
    "DescriptionFieldDescription": "Ingress som vises under tittelen. Tom = skjules.",
    "WebPartTitleInfoLabelTitle": "Mer informasjon: {0}",
    "DisplayModeFieldLabel": "Visning av invitasjonsstatus",
    "DisplayModeInlineLabel": "Vis statusliste i webdelen",
    "DisplayModeDialogLabel": "Vis i dialog (kompakt)",
    "DisplayModeFieldDescription": "Hvordan listen over tidligere invitasjoner vises: hele tabellen direkte i webdelen, eller kompakt med et sammendrag og en knapp som åpner tabellen i en dialog.",
    "InviteModeFieldLabel": "Invitasjonsmodus",
    "InviteModeSingleLabel": "Én gjest om gangen",
    "InviteModeMultiLabel": "Flere gjester om gangen",
    "InviteModeFieldDescription": "Om avsenderen kan legge til én eller flere e-postadresser i samme innsending. Ved flere gjester opprettes én forespørsel per gjest.",
    "InviteAccessLevelFieldLabel": "Hvem kan invitere gjester",
    "InviteAccessLevelOwnerLabel": "Kun gruppe-eiere",
    "InviteAccessLevelMemberLabel": "Eiere og medlemmer",
    "InviteAccessLevelAnyoneLabel": "Alle med tilgang til området",
    "InviteAccessLevelFieldDescription": "Hvem som ser webdelen og kan invitere gjester. Brukere som ikke oppfyller kravet ser ingenting — webdelen skjules helt for dem.",
    "PerGuestProfileModeFieldLabel": "Detaljer per gjest",
    "PerGuestRoleModeFieldLabel": "Rolle/brukergruppe per gjest",
    "FeatureModeDisabledLabel": "Av (skjul bryter)",
    "FeatureModeOptionalLabel": "Valgfri (bruker styrer, default av)",
    "FeatureModeEnforcedLabel": "Påkrevd (alltid på)",
    "PerGuestProfileModeFieldDescription": "Profilfelter (fornavn, etternavn, firma) per gjest. Av = feltene vises aldri; Valgfri = avsenderen kan slå dem på i draweren; Påkrevd = vises alltid.",
    "PerGuestRoleModeFieldDescription": "Rolle og SP-gruppe per gjest i stedet for felles for alle i innsendingen. Av = felles valg; Valgfri = avsenderen kan slå det på; Påkrevd = alltid per gjest.",
    "PerGuestProfileLabel": "Detaljer per gjest",
    "PerGuestRoleLabel": "Rolle og brukergruppe per gjest",
    "ViewSettingsLabel": "Visningsvalg",
    "ViewStatusButton": "Se invitasjonsstatus",
    "StatusDialogTitle": "Invitasjonsstatus",
    "StatusSummaryTotal": "{0} totalt",
    "StatusSummaryPending": "{0} venter",
    "StatusSummaryFailed": "{0} feilet",
    "CloseButton": "Lukk",
    "GuestRequestListTitleFieldLabel": "Listetittel for gjesteforespørsler",
    "GuestRequestListTitleFieldDescription": "SharePoint-listen hvor invitasjonsforespørsler lagres. Standard: Guest Requests",
    "GuestRequestSiteUrlFieldLabel": "URL til Bestillingsportalen-området",
    "GuestRequestSiteUrlFieldDescription": "URL til området hvor Guest Requests-listen ligger. Tomt = /sites/bestillingsportalen på gjeldende tenant (standard-aliaset fra installasjonen).",
    "HiddenSpGroupsFieldLabel": "Skjul SharePoint-grupper",
    "HiddenSpGroupsFieldDescription": "Komma- eller linjeseparert liste over grupper som skal skjules fra gruppevelgeren. Matcher på gruppenavn (delvis treff) eller tilgangsnivå (eksakt). Eksempel: Eiere, Full kontroll.",
    "AllowedSpGroupsFieldLabel": "Vis kun SharePoint-grupper",
    "AllowedSpGroupsFieldDescription": "Komma- eller linjeseparert liste. Hvis utfylt vises KUN grupper som matcher (på gruppenavn delvis, eller tilgangsnivå eksakt). Tomt = vis alle. Kombineres med «Skjul SharePoint-grupper» (skjul vinner). Eksempel: Eksterne, Read.",
    "InviteButton": "Inviter gjester",
    "InviteDrawerHeader": "Inviter gjester til området",
    "InviteDrawerDescription": "Skriv inn én eller flere e-postadresser. Hver gjest får en invitasjon og listet opp under når den er behandlet.",
    "GuestPickerLabel": "E-postadresse",
    "GuestPickerPlaceholder": "Skriv en e-postadresse",
    "GuestPickerInvalidEmail": "Ugyldig e-postadresse",
    "GuestPickerNoOptionsText": "Skriv inn en gyldig e-postadresse",
    "GuestPickerHelperText": "Skill flere e-poster med komma, semikolon eller linjeskift. Dersom personen finnes i Microsoft Entra, hentes profilinformasjon automatisk.",
    "FirstNameLabel": "Fornavn",
    "FirstNameDescription": "Gjestens fornavn slik det vises i Microsoft Entra.",
    "LastNameLabel": "Etternavn",
    "LastNameDescription": "Gjestens etternavn slik det vises i Microsoft Entra.",
    "CompanyLabel": "Selskap / organisasjon",
    "CompanyDescription": "Selskapet eller organisasjonen gjesten representerer.",
    "GuestExistsBadge": "Finnes i Entra ID",
    "GuestExistsMissingDetails": "Finnes i Entra ID, men mangler fornavn og/eller etternavn. Be en administrator om å oppdatere brukerens profil dersom nødvendig.",
    "NoValuePlaceholder": "Ingen verdi",
    "AccessPreviewTitle": "Tilgang gjesten får:",
    "AccessNoM365": "Ingen automatisk tilgang fra Microsoft 365-gruppen",
    "AccessNoSiteAccessWarning": "Brukeren får ingen tilgang til området — kun invitasjonen til organisasjonen. Velg rollen Gjest, legg brukeren i en SharePoint-gruppe, eller del innhold direkte senere.",
    "AccessSiteEdit": "Redigerings-tilgang på SharePoint-området",
    "AccessTeamsMember": "Medlem i Teams (chat og alle kanaler)",
    "AccessOneNotePlannerCalendar": "Tilgang til OneNote, Planner og gruppe-kalender",
    "AccessNotGroupConnectedNote": "Området er ikke koblet til en Microsoft 365-gruppe, så ingen Teams/OneNote/Planner-tilgang.",
    "AccessSpGroupAddTemplate": "Legges til i SharePoint-gruppen «{0}»",
    "AccessSpGroupCreateTemplate": "Får tilgang via ny SharePoint-gruppe «{0}» med rettighet «{1}»",
    "CancelButton": "Avbryt",
    "ClearFieldLabel": "Tøm feltet",
    "SendInvitationsButton": "Send invitasjoner",
    "RefreshButton": "Oppdater",
    "RetryButton": "Prøv på nytt",
    "StatusHeader": "Invitasjonsstatus",
    "StatusEmpty": "Ingen invitasjoner registrert for dette området ennå.",
    "StatusSearchPlaceholder": "Søk etter e-post …",
    "StatusDialogDescription": "Oversikt over invitasjoner sendt fra dette området. Bruk søk og kommandoer for å filtrere og forvalte invitasjonene.",
    "StatusDialogNoResultsLabel": "Ingen invitasjoner registrert for dette området ennå.",
    "StatusDialogNoSearchResultsLabel": "Ingen invitasjoner matchet søket ditt.",
    "StatusDialogSpinnerLabel": "Henter invitasjoner …",
    "ColumnEmail": "E-post",
    "ColumnStatus": "Status",
    "ColumnRequestedBy": "Forespurt av",
    "ColumnCreated": "Sendt",
    "ColumnError": "Feilmelding",
    "CopyRedeemUrlLabel": "Kopier invitasjonslenke",
    "CopyRedeemUrlCopied": "Kopiert!",
    "StatusPending": "Venter",
    "StatusInvited": "Invitert",
    "StatusFailed": "Feilet",
    "ToastSuccessTitle": "Invitasjoner sendt",
    "ToastSuccessBody": "Forespørslene er registrert og behandles nå i bakgrunnen.",
    "ToastErrorTitle": "Kunne ikke sende invitasjoner",
    "ToastErrorBody": "En feil oppstod. Sjekk konsollen for detaljer.",
    "M365GroupSectionTitle": "Rolle på området",
    "M365GroupRoleNoneLabel": "Ingen rolle",
    "M365GroupRoleVisitorLabel": "Besøkende",
    "M365GroupRoleMemberLabel": "Gjest",
    "M365GroupRoleOwnerLabel": "Eier",
    "M365GroupRoleSectionDescription": "Gjest legger brukeren til som gjestemedlem i Microsoft 365-gruppen — standardmodellen for eksterne i Microsoft 365. Gjesten får da tilgang til området og gruppens ressurser (Teams, Planner, SharePoint). Velg Ingen rolle og en SharePoint-gruppe under for mer begrenset tilgang.",
    "SPGroupSectionTitle": "SharePoint-brukergruppe (valgfritt)",
    "SPGroupSectionDescriptionWithGuestRole": "Gjesten får allerede tilgang via Microsoft 365-gruppen (som er medlem av områdets medlemsgruppe). Bruk dette bare for å legge gjesten til i en annen SharePoint-gruppe i tillegg.",
    "SPGroupSectionDescriptionNoRole": "Uten rollen Gjest får brukeren kun tilgang til området gjennom en SharePoint-gruppe her — eller ved at innhold deles direkte med brukeren senere.",
    "SPGroupActionNoneLabel": "Ikke legg til i SharePoint-gruppe",
    "SPGroupActionNoneWithGuestRoleLabel": "Bare legg til i standard SharePoint-medlemsgruppe",
    "SPGroupActionExistingLabel": "Legg til i eksisterende gruppe",
    "SPGroupActionNewLabel": "Opprett ny gruppe",
    "SPGroupExistingPickerLabel": "Velg gruppe",
    "SPGroupExistingPickerPlaceholder": "Velg en SharePoint-gruppe …",
    "SPGroupNewNameLabel": "Navn på ny gruppe",
    "SPGroupNewNamePlaceholder": "F.eks. Eksterne samarbeidspartnere",
    "SPGroupNewPermissionLabel": "Tilgangsnivå",
    "SPGroupNewNameRequired": "Gruppenavn er påkrevd",
    "SPPermissionRead": "Lesetilgang",
    "SPPermissionContribute": "Bidra",
    "SPPermissionEdit": "Redigering",
    "SPPermissionFullControl": "Full kontroll",
    "ColumnM365GroupRole": "M365-rolle",
    "ColumnSPGroupAction": "SP-gruppehandling",
    "ColumnSPGroupName": "SP-gruppe",
    "ColumnSPPermissionLevel": "Tilgangsnivå",
    "AccessTitle": "Ingen tilgang",
    "ErrorTitle": "Det har oppstått en feil",
    "FilterText": "Filtrer",
    "NotSpecifiedText": "Ikke angitt",
    "BooleanYes": "Ja",
    "BooleanNo": "Nei",
    "FiltersString": "Filtre",
    "Aria": {
      "MenuOverflowCount": "{0} flere elementer",
      "MoveDisabled": "Kan ikke flytte skjult kolonne",
      "MoveUp": "Flytt opp",
      "MoveUpDisabled": "Kan ikke flytte opp, øverste element",
      "MoveDown": "Flytt ned",
      "MoveDownDisabled": "Kan ikke flytte ned, nederste element",
      "Back": "Forrige/tilbake",
      "Settings": "Innstillinger",
      "Close": "Lukk"
    },
    "Placeholder": {
      "TextField": "Angi verdi her",
      "SiteName": "Angi et navn for området",
      "SiteDescription": "Angi en beskrivelse for området",
      "Icon": "Angi et ikon",
      "ChoiceField": "Velg et alternativ",
      "MultiChoiceField": "Velg ett eller flere alternativer",
      "GuestField": "Angi gjester",
      "UserField": "Angi brukere",
      "BusinessJustificationField": "Angi en forretningsmessig begrunnelse",
      "AdditionalInfoField": "Angi tilleggsinformasjon",
      "DatePicker": "Velg en dato"
    },
    "Provision": {
      "DrawerSizeFieldLabel": "Skuffestørrelse",
      "DrawerSizeMedium": "Standard",
      "DrawerSizeFull": "Fullskjerm",
      "FullscreenHeaderTitle": "Bestillingsportalen",
      "ChangeTypeButtonLabel": "Endre type",
      "DrawerLevel0HeaderText": "Bestill område",
      "DrawerLevel0DescriptionText": "Her kan du bestille et nytt område. Velg en av områdetypene under, og fyll ut informasjonen.",
      "DrawerLevel1HeaderText": "Klassifisering",
      "DrawerLevel1DescriptionText": "Her kan du velge klassifisering for området. Aktivere teams, følsomhetsetikett og oppbevaringsetikett.",
      "DrawerLevel2HeaderText": "Annen informasjon",
      "DrawerLevel2DescriptionText": "Her kan du angi annen informasjon for området. Områdebilde og oversikt over språk, tidssone og hubtilknytning.",
      "SiteTypeFieldLabel": "Områdetype",
      "SiteNameFieldLabel": "Områdenavn",
      "SiteNameFieldDescription": "Velg et unikt navn som følger organisasjonens navngivningsstandarder.",
      "SiteNamePrefixTooltipText": "Dette er et prefiks som legges til foran områdenavnet.",
      "SiteNameSuffixTooltipText": "Dette er et suffiks som legges til i enden av områdenavnet.",
      "SiteNameValidationErrorMessage": "Navnet oppgitt er ikke ledig. Prøv å endre navnet.",
      "SiteNameRequestExistsErrorMessage": "Det finnes allerede en bestilling med samme adresse. Prøv å endre navnet.",
      "SiteNameValidationSuccessMessage": "Navnet er ledig",
      "SiteDescriptionFieldLabel": "Beskrivelse",
      "SiteDescriptionFieldDescription": "Angi en beskrivelse, dette er nyttig for at folk skal forstå hva området ditt er for.",
      "BusinessJustificationFieldLabel": "Forretningsmessig begrunnelse",
      "BusinessJustificationFieldDescription": "Beskriv hvorfor du har behov for dette området? Hva er formålet?",
      "AdditionalInfoFieldLabel": "Tilleggsinformasjon",
      "AdditionalInfoFieldDescription": "Angi ytterligere informasjon vedrørende bestillingen.",
      "AliasFieldLabel": "Alias/navn",
      "UrlFieldLabel": "Områdeadresse",
      "OwnerFieldLabel": "Eier(e)",
      "OwnerFieldDescription": "Eier(e) har full tilgang til området og kan legge til og fjerne medlemmer. Du kan legge til flere eiere senere.",
      "MemberFieldLabel": "Medlem(mer)",
      "MemberFieldDescription": "Medlem(mer) har tilgang til området basert på tillatelsene som er satt. Du kan legge til flere medlemmer senere.",
      "DuplicateOwnerMemberMessage": "En bruker kan ikke være både eier og medlem. Vennligst fjern duplikaten(e).",
      "MinimumOwnersMessage": "Det kreves minst {0} eiere for denne bestillingen. Legg til flere eiere.",
      "RequestedByFieldLabel": "Bestilt på vegne av",
      "RequestedByFieldDescription": "Dersom du bestiller området på vegne av noen, kan du angi navnet på vedkommende her. Dersom du bestiller området for deg selv, kan du la feltet stå tomt.",
      "UserFieldNoOptionsText": "Ingen treff...",
      "TeamifyFieldLabel": "Aktivere Teams for området?",
      "TeamifyFieldDescription": "Om du aktiverer Teams for området, vil et Teams-område bli opprettet og knyttet til området.",
      "TeamTemplateFieldLabel": "Teams mal",
      "TeamTemplateFieldDescription": "Hvilken teams mal vil du bruke for området?",
      "ConfidentialFieldLabel": "Konfidensielle/sensitive data",
      "ConfidentialFieldDescription": "Vil konfidensielle eller sensitive data bli lagret i dette rommet? Dersom ja, må du sørge for at du har satt riktige tillatelser.",
      "PrivacyFieldLabel": "Tilgangsinnstillinger",
      "PrivacyFieldDescription": "Angi hvilken tilgangsinnstilling du ønsker for området.",
      "PrivacyFieldOptionPrivate": "Privat - Brukere trenger tillatelse for å bli med",
      "PrivacyFieldOptionPublic": "Offentlig - Alle i organisasjonen kan bli med",
      "ExternalSharingFieldLabel": "Tillat eksterne gjester",
      "ExternalSharingFieldDescription": "Dersom denne er aktivert, vil man kunne invitere inn og dele enkeltfiler, mapper, bibliotek o.l. med eksterne gjestebrukere. NB! Invitasjon av eksterne gjestebrukere vil først være mulig etter at gruppen/området er opprettet.",
      "GuestFieldLabel": "Gjest(er)",
      "GuestFieldDescription": "Gjester har begrenset tilgang til området. Du kan legge til flere gjester senere. Vennligst skriv inn en gyldig e-postadresse.",
      "GuestFieldNoOptionsText": "Kan ikke legge til...",
      "SensitivityLabelFieldLabel": "Følsomhetsetikett",
      "SensitivityLabelFieldDescription": "Hvilken følsomhetsetikett vil du anvende for området?",
      "SensitivityLabelLibraryFieldLabel": "Følsomhetsetikett for bibliotek",
      "SensitivityLabelLibraryFieldDescription": "Hvilken følsomhetsetikett vil du anvende for dokumentbiblioteket for området?",
      "RetentionLabelFieldLabel": "Oppbevaringsetikett",
      "RetentionLabelFieldDescription": "Hvilken oppbevaringsetikett vil du anvende for området?",
      "ExpirationDateFieldLabel": "Utløpsdato",
      "ExpirationDateFieldDescription": "Når utløper området? NB! Området vil ikke bli slettet etter denne datoen.",
      "ReadOnlyGroupFieldLabel": "Aktiver lesetilgangsgruppe",
      "ReadOnlyGroupFieldDescription": "Aktiver en lesetilgangsgruppe for området. Dette vil gi brukere i gruppen lesetilgang til området.",
      "InternalChannelFieldLabel": "Aktiver intern kanal",
      "InternalChannelFieldDescription": "Når dette alternativet er aktivert, vil det opprettes en intern kanal i Teams.",
      "LanguageFieldLabel": "Språk",
      "TimeZoneFieldLabel": "Tidssone",
      "HubSiteFieldLabel": "Hubtilknytning",
      "DefaultHubInfoMessage": "Dette området blir knyttet til en annen hub: {0}",
      "DefaultHubResolveErrorMessage": "Standardhuben som er angitt for denne områdetypen kunne ikke slås opp. Området blir i stedet knyttet til {0}.",
      "ParentSiteFieldLabel": "Overordnet område",
      "ParentSiteFieldDescription": "Området du bestiller vil bli koblet til det overordnede området vist her.",
      "ImageFieldLabel": "Angi områdebilde",
      "ImageFieldDescription": "Her kan du laste opp et bilde som skal brukes som områdebilde.",
      "ImageDropZoneText": "Dra og slipp bilde her, eller klikk for å velge bildefil (png, jpeg/jpg) NB! Kan ikke overstige 512 KB.",
      "ImageDropZoneErrorText": "Bildet kunne ikke lastes opp. Vennligst sørg for at filen er et bilde (png, jpeg/jpg) og ikke overstiger 512 KB.",
      "DrawerFooterDescriptionText": "Ditt område vil bli knyttet til en Microsoft 365-gruppe, som gir nettstedet ditt en delt OneNote-notatblokk, gruppe-e-postadresse og delt kalender.",
      "ProjectDataPreviewText": "Denne informasjonen vil bli angitt i prosjektinformasjonen når oppsettveiviseren kjøres",
      "PreviousButtonLabel": "Forrige",
      "NextButtonLabel": "Neste",
      "ProvisionButtonLabel": "Bestill område",
      "ToastCreatedTitle": "Området er bestilt",
      "ToastCreatedBody": "Området er nå bestilt og sendt til behandling.",
      "ToastCreatedErrorTitle": "Feil ved bestilling",
      "ToastCreatedErrorBody": "Det oppstod en feil ved bestilling av området. Vennligst prøv igjen, eller kontakt administrator.",
      "StatusMenuLabel": "Mine bestillinger",
      "SettingsMenuLabel": "Innstillinger",
      "SettingsSearchLabel": "Søk i innstillinger",
      "SettingsDialogTitle": "Innstillinger for Bestillingsportalen",
      "SettingsDialogDescription": "Her har du en oversikt over alle innstillinger for Bestillingsportalen.",
      "SettingsDialogSpinnerLabel": "Oppdaterer og henter innstillinger...",
      "SettingsDialogNoSearchResultsLabel": "Ingen innstillinger samsvarer med søket.",
      "SettingsDialogNoResultsLabel": "Det finnes ingen innstillinger for Bestillingsportalen.",
      "SettingLabel": "Innstilling",
      "DescriptionLabel": "Beskrivelse",
      "ValueLabel": "Verdi",
      "EditLabel": "Rediger",
      "StatusSearchLabel": "Søk i bestillinger",
      "UpdateLabel": "Oppdater",
      "StatusDialogTitle": "Mine bestillinger",
      "StatusDialogDescription": "Her kan du se status på dine bestillinger, hvilke områdetype, status og dato for bestillingen. Det er også mulig å slette bestillinger som ikke er sendt inn eller som har blitt avslått.",
      "StatusDialogSpinnerLabel": "Oppdaterer og henter bestillinger...",
      "StatusDialogNoSearchResultsLabel": "Ingen bestillinger samsvarer med søket.",
      "StatusDialogNoResultsLabel": "Du har ingen bestillinger, opprett en ny bestilling for å se status her.",
      "StatusLabel": "Status",
      "SubmittedLabel": "Sendt inn",
      "ApprovedLabel": "Godkjent",
      "RejectedLabel": "Avslått",
      "PendingApprovalLabel": "Venter på godkjenning",
      "SpaceCreationFailedLabel": "Områdeopprettelse feilet",
      "SpaceAlreadyExistsLabel": "Området eksisterer allerede",
      "TeamRequestedLabel": "Team forespurt",
      "SpaceCreationLabel": "Området opprettes",
      "SpaceCreatedLabel": "Området er opprettet",
      "NotSubmittedLabel": "Ikke sendt inn",
      "SubmittedDateLabel": "Bestillingsdato",
      "DeleteLabel": "Slett",
      "DeleteSubmissionLabel": "Slett bestilling",
      "DeleteSubmissionConfirmationLabel": "Er du sikker på at du vil slette bestillingen?",
      "DeletedSubmissionToastTitle": "Slettet bestilling",
      "DeletedSubmissionToastBody": "Bestillingen, {0}, er nå slettet.",
      "DeletedSubmissionErrorToastTitle": "Feil ved sletting",
      "DeletedSubmissionErrorToastBody": "Det oppstod en feil ved sletting av bestillingen. Vennligst prøv igjen, eller kontakt administrator.",
      "RequestedSource": "Prosjektportalen - Bestillingsskjema",
      "NotConfiguredTitle": "Ikke konfigurert",
      "NotConfiguredText": "Det er ikke konfigurert url til Bestillingsportalen. Vennligst angi dette i webdelen.",
      "ExpirationDateNoneOption": "Ingen utløpsdato",
      "ExpirationDateMonthOption": "{0} måned(er)",
      "NoProvisionAccessMessage": "Du har ikke tilgang til Bestillingsportalen.",
      "SiteNotFoundTitle": "Fant ikke Bestillingsportalen",
      "SiteNotFoundMessage": "Fant ikke Bestillingsportalen på {0}. Kontroller at URL-en er riktig konfigurert, eller kontakt administrator.",
      "InstancePickerTitle": "Velg bestillingsportal",
      "InstancePickerDescription": "Du har tilgang til flere bestillingsportaler. Velg hvilken du vil bruke. Valget huskes til neste gang.",
      "SwitchInstanceLabel": "Bytt bestillingsportal",
      "CurrentInstanceLabel": "Aktiv bestillingsportal: {0}",
      "ToastNameConflictErrorTitle": "Adressen er ikke ledig",
      "ToastNameConflictErrorBody": "Det finnes allerede et område eller en bestilling med samme adresse. Endre navnet og prøv igjen.",
      "ToastUserResolveErrorTitle": "Personer kunne ikke legges til",
      "ToastUserResolveErrorBody": "Én eller flere valgte personer kunne ikke knyttes til bestillingen. Søk opp personen på nytt, eller kontakt administrator.",
      "NoHubSiteConnectionMessage": "Hubtilknytning er ikke tilgjengelig. Området kan bestilles, men vil ikke bli knyttet til en hub.",
      "DefaultTeamTemplate": "Standard",
      "DefaultLanguage": "Norsk (bokmål)",
      "DefaultTimeZone": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
      "ConfirmationTitle": "Bestilling mottatt!",
      "ConfirmationMessage": "Bestillingen din er mottatt og vil bli behandlet. Du vil motta en varsling når området ditt er klart.",
      "NewRequestButton": "Ny bestilling",
      "ViewRequestsButton": "Se mine bestillinger",
      "ConfigEditorButton": "Webdel innstillinger",
      "ConfigEditorTitle": "Webdel konfigurasjon",
      "ConfigEditorDescription": "Rediger webdelens konfigurasjon i JSON-format. Endringer blir lagret i TeamsAppConfig.json og anvendt når du oppdaterer appen.",
      "ConfigJsonLabel": "Konfigurasjon (JSON)",
      "ConfigJsonHint": "Rediger JSON-konfigurasjonen. Sørg for at JSON er gyldig før du lagrer.",
      "ConfigSaveButton": "Lagre konfigurasjon",
      "ConfigSavingButton": "Lagrer...",
      "ConfigResetButton": "Tilbakestill",
      "ConfigResetConfirmationLabel": "Er du sikker på at du vil tilbakestille konfigurasjonen?",
      "ConfigSaveSuccess": "Konfigurasjon lagret. Oppdaterer...",
      "ConfigSaveSuccessTitle": "Suksess",
      "ConfigSaveError": "Kunne ikke lagre konfigurasjon",
      "ConfigInvalidJson": "Ugyldig JSON-format. Vennligst sjekk syntaksen.",
      "ConfigEditorAccessDenied": "Du må være områdeadministrator for å redigere konfigurasjonen.",
      "CommunityNameFieldLabel": "Navn på fellesskap",
      "CommunityNameFieldDescription": "Velg et unikt navn for fellesskapet som følger organisasjonens navngivningsstandarder.",
      "CommunityNameFieldPlaceholder": "Angi et navn for fellesskapet",
      "CommunityDescriptionFieldLabel": "Beskrivelse av fellesskap",
      "CommunityDescriptionFieldDescription": "Angi en beskrivelse av fellesskapet ditt, dette er nyttig for at folk skal forstå hva fellesskapet ditt er for.",
      "CommunityDescriptionFieldPlaceholder": "Angi en beskrivelse av fellesskapet",
      "CommunityJustificationFieldLabel": "Forretningsmessig begrunnelse",
      "CommunityJustificationFieldDescription": "Forklar hvorfor du har behov for dette fellesskapet.",
      "CommunityJustificationFieldPlaceholder": "Angi en forretningsmessig begrunnelse",
      "CommunityOwnerFieldLabel": "Fellesskapsadministrator(er)",
      "CommunityOwnerFieldDescription": "Hvem vil administrere dette fellesskapet? Du kan legge til flere administratorer senere.",
      "CommunityOwnerFieldPlaceholder": "Angi fellesskapsadministrator",
      "CommunityMemberFieldLabel": "Fellesskapsmedlem(mer)",
      "CommunityMemberFieldDescription": "Hvem skal være med i dette fellesskapet?",
      "CommunityMemberFieldPlaceholder": "Angi fellesskapsmedlemmer",
      "CommunityPrivacyFieldLabel": "Personvern",
      "CommunityPrivacyFieldDescription": "Velg personverninnstilling for fellesskapet.",
      "CommunityPrivacyFieldPlaceholder": "Velg personverninnstilling",
      "TeamNameFieldLabel": "Teamnavn",
      "TeamNameFieldDescription": "Gi teamet et navn",
      "TeamNameFieldPlaceholder": "Angi et navn for teamet",
      "TeamDescriptionFieldLabel": "Teambeskrivelse",
      "TeamDescriptionFieldDescription": "Angi en beskrivelse av teamet, dette er nyttig for at folk skal forstå hva teamet ditt er for.",
      "TeamDescriptionFieldPlaceholder": "Angi en beskrivelse av teamet",
      "TeamOwnerFieldLabel": "Teameier(e)",
      "TeamOwnerFieldDescription": "Hvem skal være eier(e)? Du kan legge til flere eiere senere.",
      "TeamOwnerFieldPlaceholder": "Angi teameier",
      "TeamMemberFieldLabel": "Teammedlem(mer)",
      "TeamMemberFieldDescription": "Hvem skal være med i dette teamet?",
      "TeamMemberFieldPlaceholder": "Angi teammedlemmer",
      "TeamJustificationFieldLabel": "Forretningsmessig begrunnelse",
      "TeamJustificationFieldDescription": "Forklar hvorfor du har behov for dette teamet.",
      "TeamJustificationFieldPlaceholder": "Angi en forretningsmessig begrunnelse",
      "TeamPrivacyFieldLabel": "Personvern",
      "TeamPrivacyFieldDescription": "Velg personverninnstilling for teamet.",
      "TeamPrivacyFieldPlaceholder": "Velg personverninnstilling",
      "RenderModeFieldLabel": "Visningsmodus",
      "RenderModeButton": "Knapp (åpner skuff)",
      "RenderModeInline": "Integrert skjema",
      "ButtonLabelFieldLabel": "Tekst på knapp",
      "ButtonLabelFieldDescription": "Tekst som vises på knappen for å åpne bestillingsskjemaet.",
      "ParentModeFieldLabel": "Overordnet modus",
      "ParentModeFieldDescription": "Når aktivert, vil området som bestilles bli koblet til nåværende område som et underområde. Brukes for program/overordnede områder.",
      "AutoOwnerFieldLabel": "Angi nåværende bruker som eier",
      "AutoOwnerFieldDescription": "Hvis aktivert, vil den nåværende brukeren bli satt som eier av det nye området.",
      "AutoOwnerOnText": "På",
      "AutoOwnerOffText": "Av",
      "AppearanceGroupName": "Utseende",
      "SiteTypeRenderModeFieldLabel": "Visning av områdetype",
      "SiteTypeRenderModeCardNormal": "Kort (med bilde)",
      "SiteTypeRenderModeCardMinimal": "Kort (uten bilde og beskrivelse)",
      "SiteTypeRenderModeDropdown": "Nedtrekksliste",
      "ExpirationDateModeFieldLabel": "Utløpsdato felt",
      "ExpirationDateModeDate": "Datofelt",
      "ExpirationDateModeMonthDropdown": "Nedtrekk (måneder)",
      "TitlesAndDescriptionsGroupName": "Titler og beskrivelser",
      "Level0HeaderFieldLabel": "Nivå 0 Tittel",
      "Level0HeaderFieldDescription": "Tittel som vises i første nivå.",
      "Level0DescriptionFieldLabel": "Beskrivelse",
      "Level0DescriptionFieldDescription": "Beskrivelse av nivå 0. Vises under tittel.",
      "Level1HeaderFieldLabel": "Nivå 1 Tittel",
      "Level1HeaderFieldDescription": "Tittel som vises i andre nivå.",
      "Level1DescriptionFieldLabel": "Beskrivelse",
      "Level1DescriptionFieldDescription": "Beskrivelse av nivå 1. Vises under tittel.",
      "Level2HeaderFieldLabel": "Nivå 2 Tittel",
      "Level2HeaderFieldDescription": "Tittel som vises i tredje nivå.",
      "Level2DescriptionFieldLabel": "Beskrivelse",
      "Level2DescriptionFieldDescription": "Beskrivelse av nivå 2. Vises under tittel.",
      "FooterDescriptionFieldLabel": "Bunntekst",
      "FooterDescriptionFieldDescription": "Bunntekst som vises i bunnen av bestillingsskjemaet på siste nivå.",
      "ShowHideGroupName": "Skjul/vis",
      "RequireProvisionAccessFieldLabel": "Krev tilgang til bestillingsportalen",
      "HideStatusMenuFieldLabel": "Skjul \"Mine bestillinger\" meny",
      "HideSettingsMenuFieldLabel": "Skjul \"Innstillinger\" meny",
      "AdvancedGroupName": "Avansert",
      "ProvisionUrlFieldLabel": "Provisjoneringsområde",
      "ProvisionUrlFieldDescription": "URL til området som håndterer bestillinger. Står feltet tomt brukes tenant-registeret (storage entity bp_ProvisionUrls), deretter /sites/bestillingsportalen.",
      "FieldsConfigurationLabel": "Felt konfigurasjon",
      "FieldsConfigurationPanelHeader": "Konfigurasjon av felter",
      "FieldsConfigurationManageBtnLabel": "Konfigurer felter",
      "FieldOrderLabel": "Standard rekkefølge",
      "FieldNameLabel": "Feltnavn (internt)",
      "FieldDisplayNameLabel": "Visningsnavn",
      "FieldDescriptionLabel": "Beskrivelse",
      "FieldPlaceholderLabel": "Plassholder",
      "FieldDataTypeLabel": "Felttype",
      "FieldDataTypeText": "Tekst",
      "FieldDataTypeNote": "Notat",
      "FieldDataTypeNumber": "Tall",
      "FieldDataTypeChoice": "Valg",
      "FieldDataTypeUserMulti": "Flere brukere",
      "FieldDataTypeGuest": "Gjestebrukere",
      "FieldDataTypeDate": "Dato",
      "FieldDataTypeTags": "Taksonomi",
      "FieldDataTypeBoolean": "Ja/nei",
      "FieldDataTypePercentage": "Prosent",
      "FieldDataTypeSite": "Område",
      "FieldDataTypeImage": "Bilde",
      "FieldRequiredLabel": "Påkrevd felt",
      "FieldHiddenLabel": "Skjul felt",
      "FieldLevelLabel": "Side i skjema",
      "TypeConfigurationLabel": "Konfigurasjon av typer",
      "TypeConfigurationPanelHeader": "Konfigurasjon av typer",
      "TypeConfigurationManageBtnLabel": "Konfigurer typer",
      "TypeNameLabel": "Type",
      "HiddenFieldsForTypeLabel": "Skjulte felt for denne typen",
      "HiddenFieldsForTypePlaceholder": "Velg felt å skjule...",
      "RequiredFieldsForTypeLabel": "Påkrevde felt for denne typen",
      "RequiredFieldsForTypePlaceholder": "Velg felt som skal være påkrevde...",
      "FieldConfigurationJsonLabel": "Feltkonfigurasjon (JSON)",
      "FieldConfigurationJsonPlaceholder": "Angi feltkonfigurasjon i JSON-format.",
      "PropertyEditorLabel": "Rediger webdelens egenskaper (JSON)",
      "PropertyEditorDescription": "Her kan du redigere webdelens egenskaper i JSON-format. Eksport og import av egenskaper er også mulig slik at oppsett kan gjenbrukes og importeres i andre ansattsøk webdeler.",
      "DebugModeLabel": "DebugMode",
      "DebugModeOnText": "På",
      "DebugModeOffText": "Av",
      "WebPartDescription": "Områdebestilling",
      "MissingFieldsTitle": "Manglende utfylling av følgende påkrevde felter",
      "ProvisionError": "Kunne ikke hente data fra listen '{0}', vennligst sjekk at webdelen er riktig konfigurert og at listen eksisterer på Bestillingsportalen. Error: {1}",
      "StandardTeamTemplate": "Standard team mal",
      "FieldLogicGroupName": "Feltlogikk",
      "DefaultExpirationDateFieldLabel": "Standard utløpsdato",
      "ShowTeamTemplateFieldLabel": "Vis Teams mal-felt",
      "ReadOnlyGroupLogicFieldLabel": "Krev lesetilgangsgruppe for intern kanal",
      "ProjectAreaType": "Prosjektområde",
      "VivaEngageCommunityType": "Viva Engage felleskap",
      "MicrosoftTeamsTeamType": "Microsoft Teams Team",
      "ExcludedTypesFieldLabel": "Ekskluderte områdetyper",
      "ExcludedTypesFieldDescription": "Velg områdetyper som skal skjules for brukere i denne webdelen.",
      "ProvisionAccessGroupTitleFieldLabel": "Tittel på tilgangsgruppe",
      "ProvisionAccessGroupTitleFieldDescription": "Tittelen på SharePoint-gruppen på gjeldende område som gir tilgang til bestillingsportalen. Standard er \"Bestillingsportalen\"."
    }
  }
})
