define([], function () {
  return {
    PropertyPaneDescription: 'Innstillinger for webdelen Inviter gjester.',
    BasicGroupName: 'Generelt',
    GeneralGroupName: 'Generelt',
    InviteSettingsGroupName: 'Invitasjonsoppsett',
    PerGuestGroupName: 'Funksjoner per gjest',
    DefaultsGroupName: 'Standardverdier',
    ShowHideGroupName: 'Vis/Skjul',
    DrawerShowHideGroupName: 'Vis/Skjul i invitasjons-drawer',
    StatusShowHideGroupName: 'Vis/Skjul i invitasjonsstatus',
    AdvancedGroupName: 'Avansert',
    BooleanOn: 'På',
    BooleanOff: 'Av',
    DefaultM365GroupRoleFieldLabel: 'Standard M365-rolle',
    DefaultM365GroupRoleFieldDescription: 'Forhåndsvalgt rolle når invite-drawer åpnes. Gjest = gjestemedlem i Microsoft 365-gruppen (standard gjestetilgang i Microsoft 365); eksterne kan aldri bli eiere.',
    DefaultSpGroupActionFieldLabel: 'Standard SP-gruppehandling',
    DefaultSpGroupActionFieldDescription: 'Forhåndsvalgt handling for SharePoint-brukergruppe. Standard er «Ikke legg til» — rollen Gjest gir allerede tilgang via M365-gruppen. «Legg til i eksisterende» vil pre-velge sitens Besøkende-gruppe (se også Auto-velg Besøkende-gruppe).',
    DefaultSpGroupNameFieldLabel: 'Standard SP-gruppenavn',
    DefaultSpGroupNameFieldDescription: 'Navn på en spesifikk SharePoint-gruppe som skal forhåndsvelges når «Legg til i eksisterende» er valgt. Hvis tomt brukes Besøkende-gruppen (når Auto-velg er på). Gruppen må eksistere på området.',
    PresetSpGroupNameFieldLabel: 'Forhåndsvalgt SP-gruppe',
    PresetSpGroupNameFieldDescription: 'Navn på en SharePoint-gruppe. Hvis utfylt vises et fjerde valg i drawer som legger gjesten i akkurat denne gruppen — uten dropdown. Tomt = valget skjules. Gruppen må eksistere på området.',
    SPGroupActionPresetTemplate: 'Legg til i «{0}»',
    SPGroupActionPresetLabel: 'Forhåndsvalgt gruppe',
    SpGroupOptionsGroupName: 'SharePoint-gruppevalg',
    ShowSpActionNoneFieldLabel: 'Vis valg: Ikke legg til',
    ShowSpActionExistingFieldLabel: 'Vis valg: Legg til i eksisterende',
    ShowSpActionNewFieldLabel: 'Vis valg: Opprett ny gruppe',
    ShowSpActionPresetFieldLabel: 'Vis valg: Forhåndsvalgt gruppe',
    SpGroupActionOrderFieldLabel: 'Rekkefølge på valg',
    SpGroupActionOrderFieldDescription: 'Dra for å endre rekkefølgen på SP-gruppevalgene i drawer. Synlighet styres av bryterne over.',
    DefaultSpPermissionLevelFieldLabel: 'Standard tilgangsnivå',
    DefaultSpPermissionLevelFieldDescription: 'Forhåndsvalgt tilgangsnivå når «Opprett ny gruppe» er valgt. Brukes kun når standard SP-gruppehandling = Opprett ny gruppe.',
    AutoSelectVisitorGroupFieldLabel: 'Auto-velg Besøkende-gruppe',
    AutoSelectVisitorGroupFieldDescription: 'Forhåndsvelger sitens Besøkende-gruppe når drawer åpnes (gjelder kun når standard SP-gruppehandling = Legg til i eksisterende).',
    LockM365GroupRoleFieldLabel: 'Lås standard M365-rolle',
    LockM365GroupRoleFieldDescription: 'Skjul rolle-valgene i drawer slik at brukeren kun ser standard-rollen (kan ikke endres).',
    LockSpGroupActionFieldLabel: 'Lås standard SP-gruppehandling',
    LockSpGroupActionFieldDescription: 'Skjul SP-gruppehandling-valgene i drawer slik at brukeren kun ser standard-handlingen (kan ikke endres). Underliggende felter (gruppevalg, nytt gruppenavn, tilgangsnivå) forblir tilgjengelige.',
    LockedRoleLabel: 'Rolle: {0}',
    LockedActionLabel: 'Handling: {0}',
    LockedGroupNameLabel: 'Gruppe: {0}',
    LockedFieldTooltip: 'Låst av administrator — kan ikke endres.',
    ShowAccessPreviewFieldLabel: 'Vis tilgangs-forhåndsvisning i drawer',
    ShowStatusSummaryFieldLabel: 'Vis statussammendrag (totalt/venter/feilet)',
    ShowCopyRedeemUrlFieldLabel: 'Vis Kopier-invitasjonslenke-knapp',
    ShowRetryButtonFieldLabel: 'Vis Prøv-på-nytt-knapp',
    ShowColumnM365RoleFieldLabel: 'Vis kolonne: M365-rolle',
    ShowColumnSPGroupActionFieldLabel: 'Vis kolonne: SP-gruppehandling',
    ShowColumnSPGroupNameFieldLabel: 'Vis kolonne: SP-gruppe',
    ShowColumnSPPermissionLevelFieldLabel: 'Vis kolonne: Tilgangsnivå',
    ShowM365GroupRoleSectionFieldLabel: 'Vis seksjon: Rolle på området',
    ShowSPGroupSectionFieldLabel: 'Vis seksjon: SharePoint-brukergruppe',
    TitleFieldLabel: 'Tittel',
    DescriptionFieldLabel: 'Beskrivelse',
    WebPartTitleInfoLabelTitle: 'Mer informasjon: {0}',
    DisplayModeFieldLabel: 'Visning av invitasjonsstatus',
    DisplayModeInlineLabel: 'Vis statusliste i webdelen',
    DisplayModeDialogLabel: 'Vis i dialog (kompakt)',
    InviteModeFieldLabel: 'Invitasjonsmodus',
    InviteModeSingleLabel: 'Én gjest om gangen',
    InviteModeMultiLabel: 'Flere gjester om gangen',
    InviteAccessLevelFieldLabel: 'Hvem kan invitere gjester',
    InviteAccessLevelOwnerLabel: 'Kun gruppe-eiere',
    InviteAccessLevelMemberLabel: 'Eiere og medlemmer',
    InviteAccessLevelAnyoneLabel: 'Alle med tilgang til området',
    PerGuestProfileModeFieldLabel: 'Detaljer per gjest',
    PerGuestRoleModeFieldLabel: 'Rolle/brukergruppe per gjest',
    FeatureModeDisabledLabel: 'Av (skjul bryter)',
    FeatureModeOptionalLabel: 'Valgfri (bruker styrer, default av)',
    FeatureModeEnforcedLabel: 'Påkrevd (alltid på)',
    PerGuestProfileLabel: 'Detaljer per gjest',
    PerGuestRoleLabel: 'Rolle og brukergruppe per gjest',
    ViewSettingsLabel: 'Visningsvalg',
    ViewStatusButton: 'Se invitasjonsstatus',
    StatusDialogTitle: 'Invitasjonsstatus',
    StatusSummaryTotal: '{0} totalt',
    StatusSummaryPending: '{0} venter',
    StatusSummaryFailed: '{0} feilet',
    CloseButton: 'Lukk',
    GuestRequestListTitleFieldLabel: 'Listetittel for gjesteforespørsler',
    GuestRequestListTitleFieldDescription: 'SharePoint-listen hvor invitasjonsforespørsler lagres. Standard: Guest Requests',
    GuestRequestSiteUrlFieldLabel: 'URL til Bestillingsportalen-området',
    GuestRequestSiteUrlFieldDescription: 'URL til området hvor Guest Requests-listen ligger. Tomt = /sites/bestillingsportalen på gjeldende tenant (standard-aliaset fra installasjonen).',
    HiddenSpGroupsFieldLabel: 'Skjul SharePoint-grupper',
    HiddenSpGroupsFieldDescription: 'Komma- eller linjeseparert liste over grupper som skal skjules fra gruppevelgeren. Matcher på gruppenavn (delvis treff) eller tilgangsnivå (eksakt). Eksempel: Eiere, Full kontroll.',
    AllowedSpGroupsFieldLabel: 'Vis kun SharePoint-grupper',
    AllowedSpGroupsFieldDescription: 'Komma- eller linjeseparert liste. Hvis utfylt vises KUN grupper som matcher (på gruppenavn delvis, eller tilgangsnivå eksakt). Tomt = vis alle. Kombineres med «Skjul SharePoint-grupper» (skjul vinner). Eksempel: Eksterne, Read.',

    InviteButton: 'Inviter gjester',
    InviteDrawerHeader: 'Inviter gjester til området',
    InviteDrawerDescription: 'Skriv inn én eller flere e-postadresser. Hver gjest får en invitasjon og listet opp under når den er behandlet.',
    GuestPickerLabel: 'E-postadresse',
    GuestPickerPlaceholder: 'Skriv en e-postadresse',
    GuestPickerInvalidEmail: 'Ugyldig e-postadresse',
    GuestPickerNoOptionsText: 'Skriv inn en gyldig e-postadresse',
    GuestPickerHelperText: 'Skill flere e-poster med komma, semikolon eller linjeskift. Dersom personen finnes i Microsoft Entra, hentes profilinformasjon automatisk.',
    FirstNameLabel: 'Fornavn',
    FirstNameDescription: 'Gjestens fornavn slik det vises i Microsoft Entra.',
    LastNameLabel: 'Etternavn',
    LastNameDescription: 'Gjestens etternavn slik det vises i Microsoft Entra.',
    CompanyLabel: 'Selskap / organisasjon',
    CompanyDescription: 'Selskapet eller organisasjonen gjesten representerer.',
    GuestExistsBadge: 'Finnes i Entra ID',
    GuestExistsMissingDetails: 'Finnes i Entra ID, men mangler fornavn og/eller etternavn. Be en administrator om å oppdatere brukerens profil dersom nødvendig.',
    NoValuePlaceholder: 'Ingen verdi',
    AccessPreviewTitle: 'Tilgang gjesten får:',
    AccessNoM365: 'Ingen automatisk tilgang fra Microsoft 365-gruppen',
    AccessNoSiteAccessWarning: 'Brukeren får ingen tilgang til området — kun invitasjonen til organisasjonen. Velg rollen Gjest, legg brukeren i en SharePoint-gruppe, eller del innhold direkte senere.',
    AccessSiteEdit: 'Redigerings-tilgang på SharePoint-området',
    AccessTeamsMember: 'Medlem i Teams (chat og alle kanaler)',
    AccessOneNotePlannerCalendar: 'Tilgang til OneNote, Planner og gruppe-kalender',
    AccessNotGroupConnectedNote: 'Området er ikke koblet til en Microsoft 365-gruppe, så ingen Teams/OneNote/Planner-tilgang.',
    AccessSpGroupAddTemplate: 'Legges til i SharePoint-gruppen «{0}»',
    AccessSpGroupCreateTemplate: 'Får tilgang via ny SharePoint-gruppe «{0}» med rettighet «{1}»',
    CancelButton: 'Avbryt',
    ClearFieldLabel: 'Tøm feltet',
    SendInvitationsButton: 'Send invitasjoner',
    RefreshButton: 'Oppdater',
    RetryButton: 'Prøv på nytt',

    StatusHeader: 'Invitasjonsstatus',
    StatusEmpty: 'Ingen invitasjoner registrert for dette området ennå.',
    StatusSearchPlaceholder: 'Søk etter e-post …',
    StatusDialogDescription: 'Oversikt over invitasjoner sendt fra dette området. Bruk søk og kommandoer for å filtrere og forvalte invitasjonene.',
    StatusDialogNoResultsLabel: 'Ingen invitasjoner registrert for dette området ennå.',
    StatusDialogNoSearchResultsLabel: 'Ingen invitasjoner matchet søket ditt.',
    StatusDialogSpinnerLabel: 'Henter invitasjoner …',

    ColumnEmail: 'E-post',
    ColumnStatus: 'Status',
    ColumnRequestedBy: 'Forespurt av',
    ColumnCreated: 'Sendt',
    ColumnError: 'Feilmelding',
    CopyRedeemUrlLabel: 'Kopier invitasjonslenke',
    CopyRedeemUrlCopied: 'Kopiert!',

    StatusPending: 'Venter',
    StatusInvited: 'Invitert',
    StatusFailed: 'Feilet',

    ToastSuccessTitle: 'Invitasjoner sendt',
    ToastSuccessBody: 'Forespørslene er registrert og behandles nå i bakgrunnen.',
    ToastErrorTitle: 'Kunne ikke sende invitasjoner',
    ToastErrorBody: 'En feil oppstod. Sjekk konsollen for detaljer.',

    M365GroupSectionTitle: 'Rolle på området',
    M365GroupRoleNoneLabel: 'Ingen rolle',
    M365GroupRoleVisitorLabel: 'Besøkende',
    M365GroupRoleMemberLabel: 'Gjest',
    M365GroupRoleOwnerLabel: 'Eier',
    M365GroupRoleSectionDescription: 'Gjest legger brukeren til som gjestemedlem i Microsoft 365-gruppen — standardmodellen for eksterne i Microsoft 365. Gjesten får da tilgang til området og gruppens ressurser (Teams, Planner, OneNote). Gjester kan ikke være eiere. Velg Ingen rolle og en SharePoint-gruppe under for mer begrenset tilgang.',

    SPGroupSectionTitle: 'SharePoint-brukergruppe (valgfritt)',
    SPGroupSectionDescriptionWithGuestRole: 'Gjesten får allerede tilgang via Microsoft 365-gruppen (som er medlem av områdets medlemsgruppe). Bruk dette bare for å legge gjesten til i en annen SharePoint-gruppe i tillegg.',
    SPGroupSectionDescriptionNoRole: 'Uten rollen Gjest får brukeren kun tilgang til området gjennom en SharePoint-gruppe her — eller ved at innhold deles direkte med brukeren senere.',
    SPGroupActionNoneLabel: 'Ikke legg til i SharePoint-gruppe',
    SPGroupActionExistingLabel: 'Legg til i eksisterende gruppe',
    SPGroupActionNewLabel: 'Opprett ny gruppe',
    SPGroupExistingPickerLabel: 'Velg gruppe',
    SPGroupExistingPickerPlaceholder: 'Velg en SharePoint-gruppe …',
    SPGroupNewNameLabel: 'Navn på ny gruppe',
    SPGroupNewNamePlaceholder: 'F.eks. Eksterne samarbeidspartnere',
    SPGroupNewPermissionLabel: 'Tilgangsnivå',
    SPGroupNewNameRequired: 'Gruppenavn er påkrevd',

    SPPermissionRead: 'Lesetilgang',
    SPPermissionContribute: 'Bidra',
    SPPermissionEdit: 'Redigering',
    SPPermissionFullControl: 'Full kontroll',

    ColumnM365GroupRole: 'M365-rolle',
    ColumnSPGroupAction: 'SP-gruppehandling',
    ColumnSPGroupName: 'SP-gruppe',
    ColumnSPPermissionLevel: 'Tilgangsnivå'
  };
});
