define([], function () {
  return {
    PropertyPaneDescription: 'Innstillinger for webdelen Inviter gjester.',
    BasicGroupName: 'Generelt',
    TitleFieldLabel: 'Tittel',
    DescriptionFieldLabel: 'Beskrivelse',
    WebPartTitleInfoLabelTitle: 'Mer informasjon: {0}',
    DisplayModeFieldLabel: 'Visning av invitasjonsstatus',
    DisplayModeInlineLabel: 'Vis statusliste i webdelen',
    DisplayModeDialogLabel: 'Vis i dialog (kompakt)',
    InviteModeFieldLabel: 'Invitasjonsmodus',
    InviteModeSingleLabel: 'Én gjest om gangen',
    InviteModeMultiLabel: 'Flere gjester om gangen',
    InviteAccessLevelFieldLabel: 'Hvem kan invitere gjester',
    InviteAccessLevelOwnerLabel: 'Kun gruppe-eiere',
    InviteAccessLevelMemberLabel: 'Eiere og medlemmer',
    InviteAccessLevelAnyoneLabel: 'Alle med tilgang til området',
    PerGuestProfileModeFieldLabel: 'Detaljer per gjest',
    PerGuestRoleModeFieldLabel: 'Rolle/brukergruppe per gjest',
    FeatureModeDisabledLabel: 'Av (skjul bryter)',
    FeatureModeOptionalLabel: 'Valgfri (bruker styrer, default av)',
    FeatureModeEnforcedLabel: 'Påkrevd (alltid på)',
    PerGuestProfileLabel: 'Detaljer per gjest',
    PerGuestRoleLabel: 'Rolle og brukergruppe per gjest',
    ViewStatusButton: 'Se invitasjonsstatus',
    StatusDialogTitle: 'Invitasjonsstatus',
    StatusSummaryTotal: '{0} totalt',
    StatusSummaryPending: '{0} venter',
    StatusSummaryFailed: '{0} feilet',
    CloseButton: 'Lukk',
    GuestRequestListTitleFieldLabel: 'Listetittel for gjesteforespørsler',
    GuestRequestListTitleFieldDescription: 'SharePoint-listen hvor invitasjonsforespørsler lagres. Standard: Guest Requests',
    GuestRequestSiteUrlFieldLabel: 'URL til Bestillingsportalen-området',
    GuestRequestSiteUrlFieldDescription: 'URL til området hvor Guest Requests-listen ligger (typisk Bestillingsportalen). Tomt = gjeldende område.',

    InviteButton: 'Inviter gjester',
    InviteDrawerHeader: 'Inviter gjester til området',
    InviteDrawerDescription: 'Skriv inn én eller flere e-postadresser. Hver gjest får en invitasjon og listet opp under når den er behandlet.',
    GuestPickerLabel: 'E-postadresse',
    GuestPickerPlaceholder: 'Skriv en e-postadresse',
    GuestPickerInvalidEmail: 'Ugyldig e-postadresse',
    GuestPickerNoOptionsText: 'Skriv inn en gyldig e-postadresse',
    GuestPickerHelperText: 'Skill flere e-poster med komma, semikolon eller linjeskift. Dersom personen finnes i Microsoft Entra, hentes profilinformasjon automatisk.',
    FirstNameLabel: 'Fornavn',
    FirstNameDescription: 'Gjestens fornavn slik det vises i Microsoft Entra.',
    LastNameLabel: 'Etternavn',
    LastNameDescription: 'Gjestens etternavn slik det vises i Microsoft Entra.',
    CompanyLabel: 'Selskap / organisasjon',
    CompanyDescription: 'Selskapet eller organisasjonen gjesten representerer.',
    GuestExistsBadge: 'Finnes i Entra ID',
    GuestExistsMissingDetails: 'Finnes i Entra ID, men mangler fornavn og/eller etternavn. Be en administrator om å oppdatere brukerens profil dersom nødvendig.',
    NoValuePlaceholder: 'Ingen verdi',
    AccessPreviewTitle: 'Tilgang gjesten får:',
    AccessPreviewWarningFooter: 'Vurder om dette er nødvendig — en mer begrenset rolle gir tryggere ekstern tilgang.',
    AccessFullAdminGroupConnected: 'Eier av Microsoft 365-gruppen (kan administrere Teams, kanaler og medlemmer)',
    AccessFullAdminSiteOnly: 'Full administrator-tilgang på SharePoint-området',
    AccessSiteEdit: 'Redigerings-tilgang på SharePoint-området',
    AccessSiteRead: 'Lesetilgang på SharePoint-området (via Besøkende-gruppen)',
    AccessNoM365: 'Ingen automatisk tilgang fra Microsoft 365-gruppen',
    AccessTeamsMember: 'Medlem i Teams (chat og alle kanaler)',
    AccessOneNotePlannerCalendar: 'Tilgang til OneNote, Planner og gruppe-kalender',
    AccessCanInviteOthers: 'Kan invitere flere gjester til området',
    AccessNotGroupConnectedNote: 'Området er ikke koblet til en Microsoft 365-gruppe, så ingen Teams/OneNote/Planner-tilgang.',
    AccessSpGroupAddTemplate: 'Legges til i SharePoint-gruppen «{0}»',
    AccessSpGroupCreateTemplate: 'Får tilgang via ny SharePoint-gruppe «{0}» med rettighet «{1}»',
    CancelButton: 'Avbryt',
    SendInvitationsButton: 'Send invitasjoner',
    RefreshButton: 'Oppdater',
    RetryButton: 'Prøv på nytt',

    StatusHeader: 'Invitasjonsstatus',
    StatusEmpty: 'Ingen invitasjoner registrert for dette området ennå.',
    StatusSearchPlaceholder: 'Søk etter e-post …',

    ColumnEmail: 'E-post',
    ColumnStatus: 'Status',
    ColumnRequestedBy: 'Forespurt av',
    ColumnCreated: 'Sendt',
    ColumnError: 'Feilmelding',
    CopyRedeemUrlLabel: 'Kopier invitasjonslenke',
    CopyRedeemUrlCopied: 'Kopiert!',

    StatusPending: 'Venter',
    StatusInvited: 'Invitert',
    StatusFailed: 'Feilet',

    ToastSuccessTitle: 'Invitasjoner sendt',
    ToastSuccessBody: 'Forespørslene er registrert og behandles nå i bakgrunnen.',
    ToastErrorTitle: 'Kunne ikke sende invitasjoner',
    ToastErrorBody: 'En feil oppstod. Sjekk konsollen for detaljer.',

    M365GroupSectionTitle: 'Rolle på området',
    M365GroupRoleNoneLabel: 'Ingen rolle',
    M365GroupRoleVisitorLabel: 'Besøkende',
    M365GroupRoleMemberLabel: 'Medlem',
    M365GroupRoleOwnerLabel: 'Eier',
    M365GroupRoleSectionDescription: 'På Microsoft 365-gruppe-koblede områder håndteres Eier og Medlem via gruppen (synces automatisk); Besøkende håndteres alltid via SharePoint-gruppen. På andre områdetyper håndteres alle rollene direkte via SharePoint-gruppene.',

    SPGroupSectionTitle: 'SharePoint-brukergruppe (valgfritt)',
    SPGroupActionNoneLabel: 'Ikke legg til i SharePoint-gruppe',
    SPGroupActionExistingLabel: 'Legg til i eksisterende gruppe',
    SPGroupActionNewLabel: 'Opprett ny gruppe',
    SPGroupExistingPickerLabel: 'Velg gruppe',
    SPGroupExistingPickerPlaceholder: 'Velg en SharePoint-gruppe …',
    SPGroupNewNameLabel: 'Navn på ny gruppe',
    SPGroupNewNamePlaceholder: 'F.eks. Eksterne samarbeidspartnere',
    SPGroupNewPermissionLabel: 'Tilgangsnivå',
    SPGroupNewNameRequired: 'Gruppenavn er påkrevd',

    SPPermissionRead: 'Lesetilgang',
    SPPermissionContribute: 'Bidra',
    SPPermissionEdit: 'Redigering',
    SPPermissionFullControl: 'Full kontroll',

    ColumnM365GroupRole: 'M365-rolle',
    ColumnSPGroupAction: 'SP-gruppehandling',
    ColumnSPGroupName: 'SP-gruppe',
    ColumnSPPermissionLevel: 'Tilgangsnivå'
  };
});
