blank_issues_enabled: true
contact_links:
  - name: Dokumentasjon
    url: https://github.com/Puzzlepart/bestillingsportalen#dokumentasjon
    about: Installasjons-, konfigurasjons- og oppgraderingsveiledningene, og teknisk løsningsbeskrivelse.
